// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'BANK OFFER' | 'BUNDLE' | 'DEAL' | 'FLAGSHIP' | 'FLASH SALE' | 'PERKS' | 'STUDENT';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const ONEPLUS_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'SMARTPHONES',
    title: 'Up to 50% OFF on OnePlus Phones, Audio & TVs',
    description: 'Save up to 50% on OnePlus TVs, phones, audio, and accessories — new users also get a welcome gift card worth up to ₹1,500.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-2',
    badge: '5% OFF + GIFTS',
    badgeType: 'FLAGSHIP',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'SMARTPHONES',
    title: 'OnePlus 15: 5% OFF + ₹4,000 Exchange Bonus + Free Nord Buds 3',
    description: 'Upgrade to the OnePlus 15 and save 5% instantly — plus get up to ₹4,000 exchange bonus, free Nord Buds 3 (worth ₹2,299), a phone cooler, and a 2-year battery warranty.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-3',
    badge: '18% OFF',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'SMARTPHONES',
    title: 'OnePlus 15: 18% OFF + ₹3,000 Exchange + 2% RedCoins',
    description: 'Get the OnePlus 15 at ₹69,999 with 18% off, an extra ₹3,000 exchange bonus, and up to 2% savings with RedCoins.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-4',
    badge: 'FLAT 27% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SMARTPHONES',
    title: 'OnePlus N6X: Flat 27% OFF on Burgundy Red',
    description: 'Shop the OnePlus N6X in Burgundy Red at a flat 27% discount — starting at just ₹20,999.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-5',
    badge: 'FROM ₹39,999',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SMARTPHONES',
    title: 'OnePlus 12R Starting at ₹39,999 — No Coupon Needed',
    description: 'Get the OnePlus 12R starting at ₹39,999 (8GB+128GB) with no-cost EMI options and additional bank discounts from HDFC, ICICI, and OneCard.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-6',
    badge: 'FREE BUDS 3',
    badgeType: 'BUNDLE',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'SMARTPHONES',
    title: 'OnePlus 13R: Up to ₹3,000 OFF + Free OnePlus Buds 3',
    description: 'Pick up the OnePlus 13R at an effective price of ₹39,999 — with up to ₹3,000 off on ICICI credit cards and free OnePlus Buds 3 (worth ₹6,499) on every purchase.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-7',
    badge: 'FLAT ₹1,000 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SMARTPHONES',
    title: 'OnePlus Nord 4: Flat ₹1,000 OFF + Up to ₹3,000 Bank Benefits',
    description: 'Shop the OnePlus Nord 4 starting at ₹28,999 — get a flat ₹1,000 off plus up to ₹3,000 more with selected bank cards.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-8',
    badge: 'UP TO ₹4,000 OFF',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'BANK OFFER',
    title: 'Up to ₹4,000 OFF with Axis & HDFC Bank Cards',
    description: 'Buy any OnePlus 15 or 13 model and save up to ₹4,000 with Axis or HDFC bank card offers.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-9',
    badge: 'NORD ERA',
    badgeType: 'PERKS',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SMARTPHONES',
    title: 'OnePlus Nord Era: Lifetime Display Warranty + Exclusive Perks',
    description: 'Step into the Nord Era — enjoy lifetime display warranty, Red Cable Club benefits, exchange programs, and fast free delivery on OnePlus devices.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-10',
    badge: 'AT ₹37,999',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'SMARTPHONES',
    title: 'OnePlus 13R at ₹37,999 — ₹1,500 OFF with HDFC Cards',
    description: 'Get the OnePlus 13R at an effective price of ₹37,999 with ₹1,500 off on HDFC credit cards and 6-month no-cost EMI.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-11',
    badge: '8% OFF + SBI OFFER',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'SMARTPHONES',
    title: 'OnePlus 13S: 8% OFF + Up to ₹5,000 OFF for SBI Users',
    description: 'Order the OnePlus 13S and save 8% instantly — SBI users get an additional ₹5,000 off, plus free OnePlus Nord Buds 3 on oneplus.in.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-12',
    badge: 'UP TO 17% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SMARTPHONES',
    title: 'OnePlus Nord 5: Up to 17% OFF + ₹3,000 OFF on HDFC Cards',
    description: 'Save up to 17% on the OnePlus Nord 5 and get an extra ₹3,000 off with HDFC bank credit cards — plus a free Magnetic Case on every purchase.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-13',
    badge: 'UP TO 21% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'SMARTWATCHES',
    title: 'OnePlus Wearables: Up to 21% OFF',
    description: 'Shop OnePlus wearables at the lowest prices — save up to 21% across a range of straps and wearable collections.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-14',
    badge: 'FLAT 4% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SMARTPHONES',
    title: 'OnePlus Nord CE4 Lite 5G: Flat 4% OFF + Student & Jio Benefits',
    description: 'Get a flat 4% off on the OnePlus Nord CE4 Lite 5G — students save an extra ₹250, and Jio Postpaid users unlock benefits worth ₹2,250.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-15',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'TABLETS',
    title: 'OnePlus Tablets: Up to 50% OFF',
    description: 'Upgrade your productivity — save up to 50% on OnePlus tablets and tablet accessories.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-16',
    badge: 'FLAT 18% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'EARBUDS',
    title: 'OnePlus Nord Buds 2: Flat 18% OFF — Starts at ₹2,699',
    description: 'Shop OnePlus Nord Buds 2 starting at ₹2,699 — save 18% flat with additional ₹2,000 off on ICICI bank cards and EMI.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-17',
    badge: 'FLAT 14% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'EARBUDS',
    title: 'OnePlus Buds Pro 3: Flat 14% OFF + Extra ₹1,000 on ICICI Cards',
    description: 'Upgrade your audio with the OnePlus Buds Pro 3 Series at 14% off — link your OnePlus device for an additional ₹1,000 off on ICICI bank cards.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-18',
    badge: 'FLASH SALE',
    badgeType: 'FLASH SALE',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'TABLETS',
    title: 'OnePlus Pad 2 Flash Sale: ₹34,999 + Bank Offers',
    description: 'Get the OnePlus Pad 2 at ₹34,999 in a limited-time flash sale — save up to ₹3,000 more with ICICI or OneCard and enjoy up to 9-month no-cost EMI.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-19',
    badge: '19% OFF + GIFTS',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'SMARTPHONES',
    title: 'OnePlus 11 5G: 19% OFF + ₹1,500 OFF with OneCard + Free Case',
    description: 'Shop the OnePlus 11 5G at 19% off — get ₹1,500 off on OneCard EMI, a free phone case, RedCoins, and up to 24-month no-cost EMI.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-20',
    badge: 'FLAT 25% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SMARTWATCHES',
    title: 'OnePlus Watch 2: Flat 25% OFF + Bank Card Benefits',
    description: 'Get the OnePlus Watch 2 at a flat 25% discount — with an additional ₹2,000 off via ICICI, OneCard, HDFC, or IDFC bank cards and up to 12-month no-cost EMI.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-21',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'ACCESSORIES',
    title: 'Up to 50% OFF on Mobile Accessories',
    description: 'Save up to 50% on OnePlus mobile accessories — cases, protection, cables, power, audio bundles, and more. No code needed.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-22',
    badge: 'FLAT 4% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SMARTPHONES',
    title: 'OnePlus Nord CE 2 Lite 5G: Flat 4% OFF + Spotify & Business Perks',
    description: 'Get the OnePlus Nord CE 2 Lite 5G at a flat 4% discount from ₹20,999 — with 6 months of free Spotify Premium and up to 18% savings on business purchases.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-23',
    badge: 'EXTRA 5% OFF',
    badgeType: 'STUDENT',
    badgeColor: 'bg-[#EB0028]',
    color: '#EB0028',
    type: 'STUDENT EXCLUSIVE',
    title: 'Students: Extra 5% OFF on All OnePlus Products',
    description: 'Students get an additional 5% discount on all OnePlus products — verify via UNiDAYS with your eligible OnePlus account.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-24',
    badge: 'UP TO 45% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'ACCESSORIES',
    title: 'OnePlus Bundles: Up to 45% OFF — Prices from ₹949',
    description: 'Shop OnePlus bundle collections and save up to 45% — with prices starting from just ₹949.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  }
];
