// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'CASHBACK';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const BOOKING_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'WEEKEND DEALS',
    title: 'Weekend Deals — Up to 60% Off on Stays',
    description: 'Up to 60% off on stays for weekend bookings with prices starting at ₹3,239.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-2',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#5B4FBE]',
    color: '#5B4FBE',
    type: 'INTERNATIONAL HOTELS',
    title: 'Dubai Hotels — Up to 60% Off',
    description: 'Book hotels in Dubai at up to 60% off on total room charges with select properties offering free cancellation.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-3',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF5722]',
    color: '#FF5722',
    type: 'INTERNATIONAL HOTELS',
    title: 'Sri Lanka Hotels — Up to 60% Off',
    description: 'Beachfront resorts, city hotels, and luxury stays in Sri Lanka at up to 60% off.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-4',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#4A3AFF]',
    color: '#0D9488',
    type: 'HOTELS',
    title: 'Get Up to 50% Off on Hotel Bookings Worldwide',
    description: 'Book hotels, resorts, and stays across top destinations worldwide and save up to 50% off on your room rate.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-5',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF9500]',
    color: '#FF9500',
    type: 'DOMESTIC HOTELS',
    title: 'Up to 50% Off on Puducherry Hotel Bookings',
    description: 'Puducherry stays at up to 50% off with bookings starting from ₹1,500.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-6',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#32ADE6]',
    color: '#32ADE6',
    type: 'USA HOTELS',
    title: 'USA Hotels — Up to 50% Off',
    description: 'Top-rated stays across the USA at up to 50% off covering major cities like New York, LA, San Francisco, and Chicago.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-7',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#A2845E]',
    color: '#A2845E',
    type: 'DELHI HOTELS',
    title: 'Delhi Hotels — Up to 50% Off',
    description: 'Find hotels across Delhi at up to 40-50% off covering luxury, business, and budget stays near iconic landmarks.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-8',
    badge: 'UP TO 45% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#AF52DE]',
    color: '#AF52DE',
    type: 'MUMBAI HOTELS',
    title: 'Mumbai Hotels — Up to 45% Off',
    description: 'Save up to 45% on hotel stays across Mumbai covering budget, business, and luxury options.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-9',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#34C759]',
    color: '#34C759',
    type: 'LAST-MINUTE DEALS',
    title: 'Last-Minute Stay Deals — Up to 40% Off',
    description: 'Grab last-minute deals on unsold rooms at up to 40% off the standard rate.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-10',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF2D55]',
    color: '#FF2D55',
    type: 'HOTELS SPECIAL',
    title: 'Hotels Special Offer — Up to 40% Off + Extra 10% Off with Genius',
    description: 'Top-rated hotels, resorts, and villas worldwide at up to 40% off with an extra 10% off for Genius members.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-11',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#007AFF]',
    color: '#007AFF',
    type: 'VILLAS',
    title: 'Villa Stays — Up to 40% Off',
    description: 'Luxury, private, and family-friendly villas at up to 40% off across destinations.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-12',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#5AC8FA]',
    color: '#5AC8FA',
    type: 'SINGAPORE HOTELS',
    title: 'Singapore Hotel Stays — Up to 40% Off',
    description: 'Premium, boutique, and budget-friendly hotels across Singapore locations at up to 40% off.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-13',
    badge: 'UP TO 30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FFCC00]',
    color: '#FFCC00',
    type: 'BENGALURU HOTELS',
    title: 'Bengaluru Hotels — Up to 30% Off on Selected Stays',
    description: 'Discover hotels across Bengaluru at up to 30% off on selected bookings for business and leisure travellers.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-14',
    badge: 'UP TO 30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF3B30]',
    color: '#FF3B30',
    type: 'HYDERABAD HOTELS',
    title: 'Hyderabad Hotels — Up to 30% Off',
    description: 'Hotel stays across Hyderabad at up to 30% off with pricing starting from ₹1,123.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-15',
    badge: 'UP TO 30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'BANGALORE HOTELS',
    title: 'Bangalore Hotels — Up to 30% Off',
    description: 'Save on hotel stays across Bangalore with up to 30% off close to popular attractions.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-16',
    badge: 'FLAT 20% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#5B4FBE]',
    color: '#5B4FBE',
    type: 'EARLY BIRD',
    title: 'Flat 20% Off with Early-Bird Stay Discounts',
    description: 'Plan ahead and book your stay in advance to unlock flat 20% off on eligible properties.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-17',
    badge: 'UP TO 15% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF5722]',
    color: '#FF5722',
    type: 'HOLIDAY EXCLUSIVE',
    title: 'Holiday Exclusive — Save 15% or More on Stays + Extra 10% Off with Genius',
    description: 'Knocks at least 15% off hotel bookings with an extra 10% off for Genius members.',
    code: '',
    verified: 'Verified',
    userType: 'Genius Members',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-18',
    badge: 'UP TO 15% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#4A3AFF]',
    color: '#0D9488',
    type: 'GETAWAY DEALS',
    title: 'Getaway Deals — Up to 15% Off on Eligible Stays',
    description: 'Eligible stays discounted up to 15% with an additional 10% off for Genius members on select properties.',
    code: '',
    verified: 'Verified',
    userType: 'Genius Members',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-19',
    badge: 'UP TO 15% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'GENIUS LOYALTY',
    title: 'Genius Loyalty Members Get Up to 15% Off Stays',
    description: 'Genius loyalty tier members unlock up to 15% off select properties with free breakfast or room upgrades.',
    code: '',
    verified: 'Verified',
    userType: 'Genius Members',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-20',
    badge: 'FLAT 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FF9500]',
    color: '#FF9500',
    type: 'GENIUS MEMBERSHIP',
    title: 'Flat 10% Off with Genius Membership',
    description: 'Genius Level 1 membership gives you a flat 10% off on stays at over 3,90,000 participating properties worldwide.',
    code: '',
    verified: 'Verified',
    userType: 'Genius Members',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-21',
    badge: '10% CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#32ADE6]',
    color: '#32ADE6',
    type: 'VISA CARD OFFER',
    title: 'VISA Card Offer — Up to 10% Cashback',
    description: 'Pay with a VISA card and receive up to 10% cashback on your room charges with no minimum booking value.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  }
];
