// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'CASHBACK' | 'BANK OFFER' | 'DEAL' | 'REWARDS';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const OLA_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'FLAT ₹50 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'CAB RIDES',
    title: 'Flat ₹50 OFF on Ola Mini & Prime (Hyderabad)',
    description: 'Save ₹50 on Ola Mini and Prime rides in select cities — available for select users.',
    code: 'HYD50',
    verified: 'Verified',
    userType: 'Select Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-2',
    badge: '₹300 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'OUTSTATION',
    title: '₹300 Cashback on Ola Outstation Trips in Pune',
    description: 'Pune users get ₹300 cashback on outstation Ola bookings — no minimum amount required.',
    code: 'PUNE300',
    verified: 'Verified',
    userType: 'Select Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-3',
    badge: 'FLAT ₹50 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'CAB RIDES',
    title: 'Flat ₹50 OFF on Ola Mini & Prime Rides',
    description: 'Get a flat ₹50 discount on Ola Mini and Prime rides — no minimum booking amount, applicable once per customer.',
    code: 'FLAT50',
    verified: 'Verified',
    userType: 'Select Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-4',
    badge: 'FLAT ₹50 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'CAB RIDES',
    title: 'Flat ₹50 OFF on Mini/Micro Rides (Select Users)',
    description: 'Get ₹50 off on your next Ola Mini or Micro cab ride — valid for select users in select cities for a limited period.',
    code: '50OLA',
    verified: 'Verified',
    userType: 'Select Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-5',
    badge: 'FLAT 20% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'OUTSTATION',
    title: 'Flat 20% OFF on Outstation Cab Bookings',
    description: 'Log in to the Ola app and save 20% on outstation cab bookings — book and depart within an hour.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-6',
    badge: 'UP TO 20% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'FIRST RIDE',
    title: 'New User Sign-Up: Up to 20% OFF on First Ride',
    description: 'New to Ola? Sign up today and get up to 20% off on your first ride booking.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-7',
    badge: '10% CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'CAB RIDES',
    title: '10% Cashback Up to ₹100 on Next Cab Booking',
    description: 'Get 10% cashback up to ₹100 on your next Ola cab booking — valid for all users in select cities.',
    code: 'OLA100',
    verified: 'Verified',
    userType: 'Select Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-8',
    badge: '50% OFF',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'FOOD',
    title: '50% OFF Up to ₹350 on Ola ONDC Food Orders',
    description: 'Save 50% up to ₹350 on Ola ONDC food delivery — available unlimited times for eligible users in select locations.',
    code: '50FOOD',
    verified: 'Verified',
    userType: 'Select Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-9',
    badge: '10% OFF',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'CAB RIDES',
    title: 'Standard Chartered Bank: 10% OFF on Ola Rides',
    description: 'Pay with your Standard Chartered Bank card and save an extra 10% on Ola cab rides — not valid on Ola Share or Ola Auto.',
    code: 'STANSALE10',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-10',
    badge: '₹40 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'WALLET',
    title: 'PhonePe Offer: ₹40 Cashback on First 3 Rides',
    description: 'Pay with PhonePe on your first 3 Ola rides and earn up to ₹40 cashback — available for Android app users only.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-11',
    badge: 'FLAT ₹100 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'PRIME RIDES',
    title: 'Flat ₹100 OFF on Ola Prime Rides',
    description: 'Book an Ola Prime ride and save ₹100 instantly — valid for all users on select rides.',
    code: 'IND100',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-12',
    badge: 'UP TO ₹100 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'AIRPORT',
    title: 'Airport Rides: Up to ₹100 OFF',
    description: 'Save 15% up to ₹100 on Ola airport cab bookings — available on Mini, Prime SUV, Sedan, and Play.',
    code: 'FLY100',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-13',
    badge: 'UP TO ₹40,000 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'ELECTRIC',
    title: 'Ola Electric: Up to ₹40,000 OFF with Exchange',
    description: 'Get up to ₹40,000 off on Ola S1 Pro, S1 Air, and S1 X with the exchange offer — no coupon needed.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-14',
    badge: 'FLAT 30% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'OLA RENTALS',
    title: 'Flat 30% OFF (Up to ₹250) on First Rental Booking',
    description: 'New users get 30% off up to ₹250 on their first Ola rental cab booking in select cities.',
    code: 'RENT250',
    verified: 'Verified',
    userType: 'New Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-15',
    badge: '12% OFF',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'OLA AUTO',
    title: '12% OFF on Ola Auto Rides in Hyderabad',
    description: 'Hyderabad users — save 12% on Ola Auto rides with this city-specific promo code.',
    code: 'HYD12',
    verified: 'Verified',
    userType: 'Select Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-16',
    badge: 'FLAT 18% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'CAB RIDES',
    title: 'Flat 18% OFF on Ola Mini Rides',
    description: 'Save a flat 18% on Ola Mini rides — valid for all customers in select cities.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-17',
    badge: 'FLAT 30% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'OLA RENTALS',
    title: 'Flat 30% OFF (Up to ₹30) on First Ola Rentals',
    description: 'Get 30% off on Mini/Prime rental rides — up to ₹30 maximum discount in select cities.',
    code: 'OLA30D',
    verified: 'Verified',
    userType: 'Select Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-18',
    badge: 'UP TO 20% CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'CAB RIDES',
    title: 'Up to 20% Cashback on Ola Micro, Mini & Prime',
    description: 'Save up to 20% cashback — capped at ₹50 — on Ola Micro, Mini, and Prime rides with no minimum booking required.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-19',
    badge: 'FLAT ₹20 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'OLA AUTO',
    title: 'Flat ₹20 OFF on Ola Auto Rides in Delhi',
    description: 'Delhi users — save ₹20 on every Ola Auto ride booked via the app; valid on unlimited rides.',
    code: 'DELAUTO',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-20',
    badge: 'FLAT ₹40 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'CAB RIDES',
    title: 'Flat ₹40 OFF on Ola Mini & Prime Rides in Delhi',
    description: 'Delhi riders save up to 20% — capped at ₹40 — on Ola Mini and Prime rides.',
    code: '40DEL',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-21',
    badge: '7% CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'BANK OFFER',
    title: 'Ola Money SBI Credit Card: 7% Cashback',
    description: 'Pay with your Ola Money SBI Credit Card and earn 7% cashback — up to ₹6,000 savings on Ola rides with a minimum transaction of ₹500.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-22',
    badge: 'FLAT 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'PARCEL',
    title: 'Flat 10% OFF on Ola Parcel Delivery',
    description: 'Save a flat 10% on your next Ola parcel delivery — doorstep pickup and drop available for all users.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-23',
    badge: '12% OFF',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'PRIME RIDES',
    title: '12% OFF on Ola Prime Sedan Rides',
    description: 'Ride in comfort and save 12% on Ola Prime Sedan — no code needed, available unlimited times in select locations.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-24',
    badge: '5% CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'UPI OFFER',
    title: '5% Cashback (Up to ₹35) via CRED UPI',
    description: 'Pay via CRED UPI on Ola and earn 5% cashback — up to ₹35 on a minimum payment of ₹149.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-25',
    badge: 'FROM ₹549/DAY',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'SELF DRIVE',
    title: 'Ola Self Drive Cars Starting at ₹549/Day (Bangalore)',
    description: 'Bangalore users — rent a self-drive car starting at ₹549/day inclusive of fuel; doorstep delivery available for bookings over 12 hours within 5km of pickup stations.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-26',
    badge: '7% REWARDS',
    badgeType: 'REWARDS',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'REWARDS',
    title: 'Earn 7% Reward Points on All Ola Rides',
    description: 'Ride with Ola and automatically earn 7% reward points on every trip — credited directly to your Ola Money wallet.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-27',
    badge: 'FROM ₹26',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#95C93D]',
    color: '#95C93D',
    type: 'BIKE RIDES',
    title: 'Ola Bike Rides Starting from ₹26',
    description: 'Get around the city affordably with Ola Bike rides starting at just ₹26 — available for all users, no code needed.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-28',
    badge: '8% OFF',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'OLA AUTO',
    title: '8% OFF on Ola Auto Bookings',
    description: 'Save 8% on your next Ola Auto booking — a convenient and affordable option for daily commutes.',
    code: 'AUTOLA8',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  }
];