// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'CASHBACK' | 'DIGITAL' | 'ELIGIBILITY' | 'EMI' | 'QUICK' | 'SPECIAL';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const KREDITBEE_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO ₹10 LAKHS',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'PERSONAL LOAN',
    title: 'Personal Loan | Up to Rs 10,00,000',
    description: 'Apply for a personal loan of up to Rs 10,00,000 with quick processing. Documents needed: PAN Card, Voter ID, and a selfie. Minimum monthly income of Rs 10,00,000 required.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-2',
    badge: 'UP TO ₹10 LAKHS',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'PERSONAL LOAN',
    title: 'Instant Personal Loan | Rs 6,000 to Rs 10 Lakhs',
    description: 'Borrow anywhere from Rs 6,000 up to Rs 10 Lakhs depending on your eligibility. Covers personal expenses, travel, education, and emergency needs.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-3',
    badge: 'UP TO ₹10 LAKHS',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'PERSONAL LOAN',
    title: 'Instant Loan | Up to Rs 10 Lakhs',
    description: 'Get a loan of up to Rs 10 Lakhs with quick approval. Minimal documentation required. Flexible repayment options available to match your budget.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-4',
    badge: 'UP TO ₹3 LAKHS',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'FIRST LOAN',
    title: 'New Users | Personal Loan Up to Rs 3 Lakhs',
    description: 'First-time users can apply for a personal loan starting from Rs 1,000 up to Rs 3 Lakhs. Repayment tenure between 3 and 24 months. Documents required: PAN Card plus one ID and address proof (Passport or Voter ID).',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-5',
    badge: 'UP TO ₹3 LAKHS',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'APP EXCLUSIVE',
    title: 'App Only | Flexi Loan Rs 1,000 to Rs 80,000',
    description: 'Get EMI-based loans starting from Rs 1,000 up to Rs 3 Lakhs — no credit card needed. High approval chances with minimum documentation.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-6',
    badge: 'UP TO ₹80,000',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'APP EXCLUSIVE',
    title: 'App Exclusive | Flexi Personal Loan',
    description: 'Sign up on the KreditBee app and apply for a flexi personal loan. Borrow between Rs 1,000 and Rs 80,000 based on your eligibility. Use the loan amount for any personal need.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-7',
    badge: 'UP TO ₹750 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'REFERRAL',
    title: 'Referral Offer | Earn Up to Rs 750 Cashback',
    description: 'Refer a friend to KreditBee and earn cashback of up to Rs 750. Visit the KreditBee website or app for full referral programme details.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-8',
    badge: 'CREDIT LINE',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'PERSONAL LOAN',
    title: 'Explore KreditBee Credit Line Offers',
    description: 'Check available offers on the KreditBee credit line facility for eligible users through the app.',
    code: 'KB300',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-9',
    badge: 'EMI OFFER',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'EMI OFFERS',
    title: 'Flexible EMI Plan Options on Your KreditBee Loan',
    description: 'Explore flexible EMI plan options available on eligible KreditBee personal loans.',
    code: 'KB200',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-10',
    badge: 'REFERRAL OFFER',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'APP EXCLUSIVE',
    title: 'Refer a Friend and Check for Referral Rewards',
    description: 'Invite friends to the KreditBee app and check the current referral programme for available rewards.',
    code: 'KBREFER',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-11',
    badge: 'SPECIAL OFFER',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'FIRST LOAN',
    title: 'Special Offer for First-Time KreditBee Loan Applicants',
    description: 'New to KreditBee? First-time applicants can check for special offers available at the time of their first loan application.',
    code: 'KB100',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-12',
    badge: 'FEE WAIVER',
    badgeType: 'FREE',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'PROCESSING FEE',
    title: 'Festive Special | Processing Fee Waiver',
    description: 'Limited-period festive offer with special benefits on processing fees. Reduce your upfront borrowing cost during the festive season.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-13',
    badge: 'REDUCED FEE',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'PROCESSING FEE',
    title: 'Reduced Processing Fee on Your Personal Loan Application',
    description: 'Apply for a personal loan through KreditBee and enjoy a reduced processing fee on eligible applications.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-14',
    badge: 'PROCESSING FEE',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'PROCESSING FEE',
    title: 'Special Offer on Processing Fee for Returning Users',
    description: 'Existing KreditBee users can check the app for special offers on processing fees for repeat loan applications.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-15',
    badge: 'FROM 12% P.A.',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'PERSONAL LOAN',
    title: 'Interest Rates Starting from 12% p.a.',
    description: 'Competitive interest rates on eligible loans, starting from 12% per annum. Transparent loan terms with no hidden charges. Check your eligibility and apply online.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-16',
    badge: 'APP EXCLUSIVE',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'APP EXCLUSIVE',
    title: 'App-Exclusive Offers on the KreditBee Mobile App',
    description: 'Download the KreditBee app and check for app-exclusive offers on your next loan application.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-17',
    badge: 'FREE CHECK',
    badgeType: 'FREE',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'PERSONAL LOAN',
    title: 'Free Eligibility Check Before You Apply for a Personal Loan',
    description: 'Check your loan eligibility on the KreditBee app or website before submitting your personal loan application.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-18',
    badge: 'QUICK PROCESS',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'PERSONAL LOAN',
    title: 'Faster Application Processing on Select KreditBee Loans',
    description: 'Select KreditBee loan applications may be eligible for faster processing through the app.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-19',
    badge: 'REPEAT USERS',
    badgeType: 'SPECIAL',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'EXCLUSIVE',
    title: 'Repeat Users | Exclusive Benefits for Existing Customers',
    description: 'Existing KreditBee customers get a smoother loan experience on repeat applications. Faster approvals with a simplified application flow.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-20',
    badge: '100% ONLINE',
    badgeType: 'DIGITAL',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'PERSONAL LOAN',
    title: '100% Online Loan Application',
    description: 'Complete your entire loan application digitally — no branch visit needed. Fully paperless process from application to disbursal.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-21',
    badge: 'NEW USER OFFER',
    badgeType: 'SPECIAL',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'FIRST LOAN',
    title: 'New User Offer | First Loan Benefits',
    description: 'First-time applicants can complete the loan process entirely online. Fast approvals with straightforward documentation.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-22',
    badge: 'FAST DISBURSAL',
    badgeType: 'QUICK',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'PERSONAL LOAN',
    title: 'Loan in Minutes | Fast Disbursal',
    description: 'Quick approval and fast fund transfer to your bank account. Suited for urgent financial requirements.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-23',
    badge: 'FLEXIBLE EMI',
    badgeType: 'EMI',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'EMI OFFERS',
    title: 'Flexible EMI Options',
    description: 'Choose a repayment tenure that fits your monthly budget. Plan and manage your EMIs with greater control over your finances.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-24',
    badge: '24X7 ACCESS',
    badgeType: 'DIGITAL',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'PERSONAL LOAN',
    title: '24x7 Instant Loan Applications',
    description: 'Apply for a loan at any time — the platform is available around the clock. Fast access to funds whenever you need them.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-25',
    badge: 'EASY KYC',
    badgeType: 'DIGITAL',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'PERSONAL LOAN',
    title: 'Hassle-Free Documentation',
    description: 'Submit basic KYC and income documents online. Simplified verification process with minimal back-and-forth.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-26',
    badge: 'SHOPPING LOAN',
    badgeType: 'SPECIAL',
    badgeColor: 'bg-[#0D2A4D]',
    color: '#0D2A4D',
    type: 'SHOPPING',
    title: 'Finance Your Shopping with Easy Loans',
    description: 'Fund electronics, appliances, and other purchases without waiting. Convert the loan into manageable monthly repayments.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-27',
    badge: 'FOR ALL',
    badgeType: 'ELIGIBILITY',
    badgeColor: 'bg-[#1B6FE0]',
    color: '#1B6FE0',
    type: 'PERSONAL LOAN',
    title: 'Loans for Salaried & Self-Employed Individuals',
    description: 'Loan options available for both salaried professionals and self-employed applicants. Flexible borrowing based on individual eligibility.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  }
];
