// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const AMAZON_COUPONS: Coupon[] = [
    {
      id: 'coupon-1',
      badge: 'UP TO 90% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'ELECTRONICS',
      title: 'Save Up to 90% Off Electronics, Fashion, Beauty & More',
      description: 'Shop electronics, fashion, beauty and more from leading top brands with daily discounts — no coupon code required.',
      code: '',
      verified: 'Verified',
      userType: 'New User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-2',
      badge: 'UP TO 65% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'ALL CATEGORIES',
      title: 'Get Up To 65% OFF On Selected Products Across All Categories!',
      description: 'Save up to 65% on handpicked items across electronics, fashion, home essentials, beauty and more — deals vary by category.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-3',
      badge: 'UP TO 60% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'BESTSELLERS',
      title: 'Amazon Bestsellers - Up To 60% OFF On Hand Picked Items!',
      description: 'Save big on Amazon Best Sellers — from tech and kitchen gadgets to fashion and beauty, curated favorites at unbeatable prices.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-4',
      badge: 'UP TO 80% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'PRIME - MEDS',
      title: 'Prime Members Special - Save Up To 80% On Meds',
      description: 'Exclusive savings for Prime members — save up to 80% on medicines, with prices starting at just $10.',
      code: '',
      verified: 'Verified',
      userType: 'New User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-5',
      badge: 'SAVE 62% OFF',
      badgeType: 'FLAT',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'ELECTRONICS',
      title: 'Flat 62% OFF On JBL Live 670NC - Wireless On-Ear Headphones',
      description: 'Enjoy wireless noise-cancelling headphones with up to 65 hours battery life — no coupon code required, available in 4 colors.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-6',
      badge: 'UP TO 60% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'GARDEN & OUTDOOR',
      title: 'Save Up to 60% Off On Garden And Outdoor',
      description: 'Avail up to 60% off on garden tools, pest control, outdoor storage, grills and more — open to everyone.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-7',
      badge: 'UP TO 56% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'BEAUTY & PERSONAL CARE',
      title: 'Beauty & Personal Care Offer - Enjoy Up To 56% OFF',
      description: 'Enjoy up to 56% off on top-rated skincare items — valid on select products, discount applied automatically at cart.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-8',
      badge: 'DEAL',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'HOME ESSENTIALS',
      title: 'Shop Amazon Home Essentials Starting At Exciting Prices',
      description: 'Explore stylish furniture, decor, bedding, bath and premium kitchen products to refresh your living space today.',
      code: '',
      verified: 'Verified',
      userType: 'New User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-9',
      badge: 'UP TO 58% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'SMART HOME',
      title: 'Save Up to 58% on Smart Home Security Cameras',
      description: 'Get 40% off select Ring Video Doorbells and up to 49% off eligible Blink cameras — smart security devices starting at $29.99.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-10',
      badge: 'BEST OFFER',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'FASHION',
      title: 'Get Up To 55% OFF On Preferred Fashion Products',
      description: 'Save up to 55% off on limited fashion products — the latest clothing, accessories and footwear in multiple sizes for men and women.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-11',
      badge: 'UP TO 51% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'ELECTRONICS',
      title: 'On Wireless Headphones Save Up To 51% OFF',
      description: 'Save up to 51% on Bluetooth headsets, EarPods and earbuds from top brands — perfect for calls, music, workouts and commutes.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-12',
      badge: '15% OFF',
      badgeType: 'PERCENT',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'LUXURY FASHION',
      title: 'Save 15% on Luxury Designer Handbags Today',
      description: 'Shop Louis Vuitton, Dior, Gucci and Hermes pieces at 15% savings — upgrade your collection with luxury resale deals.',
      code: '',
      verified: 'Verified',
      userType: 'New User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-13',
      badge: 'UP TO 50% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'TOYS & GAMES',
      title: 'Enjoy Up To 50% Off On Toys & Games',
      description: 'Save up to 50% on Arts & Crafts, Baby & Toddler Toys, Building Toys, Dolls and Dress Up sets — prices starting at just $1.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-14',
      badge: 'BEST DEAL',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'SMART HOME',
      title: 'Save Up To 50% OFF On Smart Home Accessories',
      description: 'Save up to 50% on smart lighting, entry systems, security cameras and more to improve your home for less — available to everyone.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-15',
      badge: 'UP TO 40% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'SMART HOME',
      title: 'Ring Indoor Cam 1080p HD Available With 40% Off',
      description: 'Get the Ring Indoor Cam 1080p HD with 40% off — perfect for monitoring your home or business with complete app control.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-16',
      badge: 'UP TO 50% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'BEAUTY & PERSONAL CARE',
      title: 'Save Up To 50% OFF On Tretinoin Treatment',
      description: 'Save up to 50% on Tretinoin Cream anti-aging skin care — reduces fine lines, lightens sun spots, no coupon needed.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-17',
      badge: 'UP TO 46% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'HOME ESSENTIALS',
      title: 'Home Essentials - Up to 46% Off On Your Purchases',
      description: 'Get up to 46% off on home decor, furniture, kitchen & dining and area rugs — prices start from $9, open to all users.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-18',
      badge: '43% DISCOUNT',
      badgeType: 'PERCENT',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'SMART HOME',
      title: '43% OFF On Ring Battery Doorbell + Pan-Tilt Cam Combo',
      description: 'Secure your home with the Ring Battery Doorbell and Pan-Tilt Indoor Cam bundle for just $79.99, saving $60 (43%).',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-19',
      badge: 'UP TO 40% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'HOME & TOYS',
      title: 'Home Appliances & Toys Savings - Get Up To 40% OFF',
      description: 'Save up to 40% on home appliances, toys and fashion picks — no coupon code needed, savings apply automatically.',
      code: '',
      verified: 'Verified',
      userType: 'New User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-20',
      badge: 'HOT DEAL',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'SPORTS & OUTDOOR',
      title: 'Sports And Outdoor - Up to 40% Off On Products',
      description: 'Enjoy up to 40% off on exercise & fitness, hunting & fishing, sports clothing and outdoor gear — all users eligible.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-21',
      badge: 'UP TO 36% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'ELECTRONICS',
      title: 'Electronics - Enjoy Up To 36% On Hand Picked Products',
      description: 'Get up to 36% off on cell phones, computers & accessories, video games, televisions and headphones — select items only.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-22',
      badge: 'UP TO 35% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'KITCHEN APPLIANCES',
      title: 'Kitchen Appliances - Up To 35% OFF',
      description: 'Get up to 35% off on ice cream makers, airfryers, multicookers and more kitchen appliances — limited time only.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-23',
      badge: 'UP TO 34% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'ELECTRONICS',
      title: 'Save Up To 34% OFF On Amazon Kids Echo Devices',
      description: 'Exclusive sale on Amazon Echo devices for kids — up to 34% off Alexa-enabled gadgets, discount applies automatically.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-24',
      badge: 'UP TO 30% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'FASHION',
      title: 'Save Up To 30% OFF On Selected Packable Rain Jackets',
      description: 'Get up to 30% off handpicked women\'s packable rain jackets — ultra-lightweight, waterproof, available in all sizes and colors.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-25',
      badge: 'UP TO 30% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'ELECTRONICS',
      title: 'Computers, Tablets and IT Accessories - Up To 30% OFF',
      description: 'Save up to 30% on laptops, desktops, monitors, gaming systems, tablets and storage devices — deals start from $19.99.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-26',
      badge: 'UP TO 30% OFF',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'GROCERY',
      title: 'Save Big On The Plant Protein Powder Brand | Up To 30% OFF',
      description: 'Enjoy up to 30% off on Organic Protein Shakes, Grass-Fed Dairy options and other health-focused products — limited time offer.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-27',
      badge: '20% OFF',
      badgeType: 'PERCENT',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'ELECTRONICS',
      title: 'Get 20% OFF On Amazon Devices With Trade-in',
      description: 'Enjoy 20% off Amazon Devices with a trade-in — no coupon code required, receive your value as an Amazon.com Gift Card.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-28',
      badge: '20% DISCOUNT',
      badgeType: 'PERCENT',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'BEAUTY & PERSONAL CARE',
      title: 'Get 20% OFF On Collagen Night Wrapping Mask',
      description: 'Get 20% off on Collagen Night Wrapping Mask — priced at $18.90, drops to $15.20 after discount, no code needed.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-29',
      badge: 'NEW ARRIVALS',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'NEW RELEASES',
      title: 'Hot New Releases - The Price Range Starts From $4.99',
      description: 'Shop newly released products from $4.99 across Kitchen & Dining, Pet Supplies, Sports & Outdoors, Clothing and Beauty.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-30',
      badge: 'FROM $6',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'PARTY SUPPLIES',
      title: 'Backdrop Silver Metallic Tinsel Foil Fringe Curtains Starts From $5.99',
      description: 'Buy Silver Metallic Tinsel Foil Fringe Backdrop Curtains from $5.99 — perfect for birthdays, weddings and celebrations, 2-panel pack.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-31',
      badge: 'GIFT CARDS',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'GIFT CARDS',
      title: 'Gift Cards Begin From $10',
      description: 'Amazon gift cards available from $10, redeemable within the United States — all sales final, non-refundable and non-transferable.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-32',
      badge: 'FROM $20',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'FASHION',
      title: 'Crocs Kids\' Classic Clog Starts From $19.98',
      description: 'Crocs Kids\' Classic Clogs start at $19.98 — comfortable Croslite material in a variety of fun colors and sizes.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-33',
      badge: '$25',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'GROCERY',
      title: 'Unwell Hydration Drinks - Starting At $25',
      description: 'Budget-friendly wellness hydration drinks starting at $25 — available in Orange, Strawberry and Mango flavors.',
      code: '',
      verified: 'Verified',
      userType: 'New User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-34',
      badge: 'UNDER $30',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'SPORTS & FITNESS',
      title: '4+ Star Fitness Faves Under $30',
      description: 'Get fit for less with 4+ star rated fitness equipment under $30 — limited time offer on top favorites.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-35',
      badge: 'FROM $35',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'ELECTRONICS',
      title: 'The Echo & Alexa Speakers Price Starts From $34.99',
      description: 'Get Alexa and Echo smart speakers and displays starting from $34.99 — prices vary depending on features chosen.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-36',
      badge: '$36',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'HOME & KITCHEN',
      title: 'SDIII 3PCS Blue Butterfly Comforter Set Twin For $35.99',
      description: 'Get the SDIII 3PCS Blue Butterfly Comforter Set Twin with 2 pillowcases for $35.99 — lightweight microfiber design.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-37',
      badge: 'UNDER $50',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'KITCHEN APPLIANCES',
      title: 'Purchase Kitchen Essentials Under $50',
      description: 'Get Toasters, Popcorn Makers, Cookers, Kettles and more kitchen essentials under $50 — high quality, open to all users.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-38',
      badge: 'FROM $70',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'LUXURY BEAUTY',
      title: 'Luxury Beauty Essentials - Prices Starting From $70',
      description: 'Upgrade your routine with premium skincare, haircare, makeup and fragrance collections starting at just $70.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-39',
      badge: 'FROM $169',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'SMART HOME',
      title: 'Blink Outdoor 4, Wire-free Smart Security Camera Price Begins From $169',
      description: 'Order the Blink Outdoor 4 wire-free smart security camera from $169 — two-way audio, HD live view and motion detection.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-40',
      badge: '$599',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'ELECTRONICS',
      title: 'New MacBook Neo Starting at $599',
      description: 'Shop the new MacBook Neo on Amazon starting at $599 — powerful performance and sleek design for work and everyday productivity.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-41',
      badge: 'NEW USER OFFER',
      badgeType: 'FREE',
      badgeColor: 'bg-[#232F3E]',
      color: '#232F3E',
      type: 'PRIME',
      title: 'New Member Offer: 30-Day Free Trial On Prime Membership',
      description: 'Enjoy a 30-day free trial on Prime Membership — join with your email ID and get fast delivery, free shipping and more, for new users only.',
      code: '',
      verified: 'Verified',
      userType: 'New User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-42',
      badge: 'DEAL',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#FF9900]',
      color: '#FF9900',
      type: 'PET SUPPLIES',
      title: 'Pet Medications At Less Price',
      description: 'Affordable prescription medications for your pets from $20 — hassle-free home delivery on a broad range of pet food and health products.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    },
    {
      id: 'coupon-43',
      badge: 'OFFER',
      badgeType: 'UP TO',
      badgeColor: 'bg-[#5B4FBE]',
      color: '#5B4FBE',
      type: 'FASHION',
      title: 'New on Amazon - Shop Iconic Chuck Taylor Converse Sneakers',
      description: 'Fresh arrival: Iconic Chuck Taylor Converse sneakers on Amazon — comfortable, stylish kicks for every style and occasion.',
      code: '',
      verified: 'Verified',
      userType: 'Existing User',
      validTill: '30 Jun 2026'
    }
  ];
