// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'DEAL';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const REDBUS_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'FIRST BOOKING',
    title: 'New redBus Users — 12% OFF + 12% Cashback Up to ₹500 on Bus Tickets',
    description: 'First-time redBus users can save 12% instantly plus earn 12% cashback on bus ticket bookings — combined benefit of up to ₹500 on orders above ₹200.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-2',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'ONAM SALE',
    title: 'redBus Onam Sale — 12% OFF + 12% Cashback Up to ₹500 on Bus Bookings',
    description: 'Book bus tickets during the redBus Onam Sale and save 12% instantly plus earn 12% cashback — up to ₹500 combined on bookings above ₹200.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-3',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'SOUTH ROUTES',
    title: 'Book Bangalore & Chennai Bus Tickets — Up to ₹500 OFF from ₹645',
    description: 'Book Bangalore and Chennai route bus tickets on redBus and save up to ₹500 — fares start from ₹645 with the coupon code applied at checkout.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-4',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'AP & TELANGANA',
    title: 'AP & Telangana Bus Tickets — 12% OFF + 12% Cashback Up to ₹500 on redBus',
    description: 'Book Andhra Pradesh and Telangana route bus tickets on redBus and save 12% instantly plus earn 12% cashback — combined benefit up to ₹500.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-5',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'SOUTH ROUTES',
    title: 'Karnataka, Tamil Nadu & Kerala Bus Tickets — Up to ₹500 OFF on redBus',
    description: 'Book bus tickets on Karnataka, Tamil Nadu, and Kerala routes on redBus and save up to ₹500 — minimum booking of ₹200, valid once per new user.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-6',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'STUDENT OFFER',
    title: 'redBus Student Offer — Up to ₹500 OFF on Bus Ticket Bookings',
    description: 'First-time redBus users including students can save up to ₹500 on bus bookings — valid on the redBus app, mobile web, and desktop from ₹645.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-7',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'AC BUSES',
    title: 'Book AC Bus Tickets on redBus — Up to ₹500 OFF for New Users',
    description: 'Book AC bus tickets on redBus and save up to ₹500 — valid for first-time users on bookings above ₹200, one use per email or mobile number.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-8',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'WEST ROUTES',
    title: 'Maharashtra & UP Bus Tickets on redBus — Up to ₹500 OFF',
    description: 'Book bus tickets on Maharashtra and Uttar Pradesh routes on redBus and save up to ₹500 — apply the coupon code at checkout on bookings above ₹200.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-9',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'EAST ROUTES',
    title: 'East India Bus Tickets on redBus — Up to ₹500 OFF on Kolkata, Guwahati & More',
    description: 'Book bus tickets on East India routes including Kolkata, Guwahati, Patna, and Bhubaneswar on redBus — save 12% plus 12% cashback up to ₹500.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-10',
    badge: 'FROM ₹450',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'POPULAR ROUTE',
    title: 'Hyderabad to Vijayawada Bus Tickets — Up to ₹500 OFF from ₹450 on redBus',
    description: 'Book Hyderabad to Vijayawada bus tickets on redBus at the lowest fares — apply the coupon code and save up to ₹500 on bookings starting from ₹450.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-11',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'POPULAR ROUTE',
    title: 'Pune & Jaipur Bus Tickets on redBus — Up to ₹500 OFF for New Users',
    description: 'Book bus tickets on Pune and Jaipur routes on redBus and save up to ₹500 — minimum booking of ₹200 required, apply coupon code at checkout.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-12',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'POPULAR ROUTE',
    title: 'Lucknow & Mumbai Bus Tickets on redBus — Up to ₹500 OFF',
    description: 'Book bus tickets on Lucknow and Mumbai routes on redBus and save up to ₹500 — apply the coupon code at checkout to activate the discount.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-13',
    badge: 'FROM ₹645',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'POPULAR ROUTE',
    title: 'Hyderabad to Bangalore Bus Tickets — Up to ₹500 OFF from ₹645 on redBus',
    description: 'Book Hyderabad to Bangalore bus tickets on redBus at fares starting from ₹645 — apply the coupon code at checkout and save up to ₹500.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-14',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'NORTH ROUTES',
    title: 'Delhi & Rajasthan Bus Tickets on redBus — Up to ₹500 OFF for New Users',
    description: 'Book bus tickets on Delhi and Rajasthan routes on redBus and save up to ₹500 — minimum booking of ₹200 required, new users only.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-15',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'WEST ROUTES',
    title: 'West India Bus Tickets on redBus — Up to ₹500 OFF on Indore, Nagpur & Nashik Routes',
    description: 'Book bus tickets on West India routes including Indore, Nagpur, and Nashik on redBus — apply the coupon code at checkout and save up to ₹500.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-16',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'POPULAR ROUTE',
    title: 'Bhopal Bus Tickets on redBus — Up to ₹500 OFF for First-Time Users',
    description: 'Book bus tickets on the Bhopal route on redBus and save up to ₹500 — minimum booking of ₹200 required, valid for first-time users only.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-17',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'CENTRAL ROUTES',
    title: 'Gujarat & MP Bus Tickets on redBus — Up to ₹500 OFF for New Users',
    description: 'Book bus tickets on Gujarat and Madhya Pradesh routes on redBus and save up to ₹500 — apply the coupon code at checkout, valid for new users only.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-18',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'TGSRTC',
    title: 'Book TGSRTC Bus Tickets on redBus — Up to ₹500 OFF for New Users',
    description: 'Book TGSRTC bus tickets on redBus and save up to ₹500 — minimum transaction of ₹200 required, valid once per new user (per email or mobile number).',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-19',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'POPULAR ROUTE',
    title: 'Ahmedabad Bus Tickets on redBus — Up to ₹500 OFF for First-Time Users',
    description: 'Book bus tickets on the Ahmedabad route on redBus and save up to ₹500 — minimum booking of ₹200 required, valid for first-time redBus users only.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-20',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'APSRTC',
    title: 'Book APSRTC Bus Tickets on redBus — 12% OFF + 12% Cashback Up to ₹500',
    description: 'Book APSRTC bus tickets on redBus and save 12% instantly plus earn 12% cashback — combined benefit up to ₹500 on bookings above ₹200.',
    code: 'RBCC500',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-21',
    badge: 'UP TO ₹500 OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D84E55]',
    color: '#D84E55',
    type: 'BANK OFFER',
    title: 'IDFC FIRST Bank Credit Card Offer — Up to ₹500 OFF on redBus Bus Tickets',
    description: 'Pay with an IDFC FIRST Bank Credit Card on redBus and save up to ₹500 on bus ticket bookings — valid on Saturdays and Sundays only, excluding RTC operators.',
    code: 'IDFC500',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  }
];
