// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const NYKAA_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'SITEWIDE',
    title: 'Nykaa Sitewide Sale — Up to 60% OFF + Extra 20% with Coupon + Free Shipping',
    description: 'Shop across all Nykaa categories on the app and save up to 60% — apply the coupon code for an extra 20% off, plus free shipping on orders above ₹299.',
    code: 'EXTRA20',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-2',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'FLASH DEALS',
    title: 'Nykaa Flash Deals — Up to 50% OFF + Extra 15% for First-Time Shoppers',
    description: 'First-time Nykaa shoppers can save up to 50% on beauty products — apply the coupon code for an extra 15% off (up to ₹300) on prepaid orders.',
    code: 'NEW15',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-3',
    badge: 'FREE GIFT',
    badgeType: 'FREE',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'BEAUTY SALE',
    title: 'Nykaa Best of Beauty Sale — Up to 60% OFF + Extra 10% via Bank + Free Gift',
    description: "Shop Nykaa's Best of Beauty Sale and save up to 60% — earn a free gift on orders above ₹1,600 and get an extra 10% off via select bank cards.",
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-4',
    badge: 'EXTRA 5% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'LOYALTY OFFER',
    title: 'Nykaa Loyalty Offer — Up to 50% OFF + Extra 5% on Your 3rd Order',
    description: 'Returning Nykaa shoppers save up to 50% on beauty — apply the coupon code on your 3rd order with a minimum spend of ₹1,200 for an extra 5% off.',
    code: 'NYK3RD',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-5',
    badge: 'EXTRA 5% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'REPEAT ORDER',
    title: 'Nykaa 2nd Order Offer — Up to 50% OFF + Extra 5% on Your Second Purchase',
    description: 'Save up to 50% on beauty products on your second Nykaa order — apply the coupon code for an extra 5% off with a minimum spend of ₹800, plus free shipping above ₹299.',
    code: 'NYK2ND',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-6',
    badge: 'FLAT ₹400 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'APP EXCLUSIVE',
    title: 'Nykaa App Exclusive — Flat ₹400 OFF on Your First Order Above ₹1,500',
    description: 'First-time Nykaa app shoppers can save flat ₹400 on orders of ₹1,500 or more — apply the coupon code at checkout on selected brands.',
    code: 'EXTRA400I',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-7',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'CLEARANCE',
    title: 'Nykaa Beauty Clearance Sale — Up to 60% OFF + Extra 10% via Bank Cards',
    description: "Shop Nykaa's Beauty Clearance Sale across makeup, skincare, haircare, and more — save up to 60% with additional 10% off via select bank credit cards.",
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-8',
    badge: 'UP TO 55% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'SKINCARE',
    title: 'Nykaa Skincare Sale — Up to 55% OFF + Extra 20% for New App Users',
    description: 'Shop skincare on the Nykaa app during the sale and save up to 55% — apply the coupon code for an extra 20% off on orders above ₹500, valid for new app users.',
    code: 'EXTRA20',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-9',
    badge: 'FLAT ₹2,000 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'DYSON',
    title: 'Save Flat ₹2,000 on Dyson Orders at Nykaa',
    description: 'Shop any Dyson product on Nykaa and save flat ₹2,000 — the coupon can be combined with other active offers on the same order.',
    code: 'DYSONAUG2K',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-10',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'MAKEUP',
    title: 'Nykaa Makeup Mega Deals — Up to 60% OFF + Extra 20% with Coupon',
    description: "Shop Nykaa's makeup range at up to 60% off and apply the coupon code for an extra 20% off — covers lipsticks, foundations, eyeshadow, concealers, and more.",
    code: 'EXTRA20',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-11',
    badge: 'EXTRA 15% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'HAIR CARE',
    title: 'Nykaa Hair Deal — Buy 3 Items & Get Extra 15% OFF on Hair Care',
    description: 'Add any 3 hair care items to your Nykaa cart and save an extra 15% — the coupon can be stacked with other active offers on your order.',
    code: 'HAIRDAY2',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-12',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'HAIR CARE',
    title: 'Nykaa Hair Care Sale — Up to 60% OFF + Extra 20% with Coupon',
    description: "Shop Nykaa's full hair care range at up to 60% off — apply the coupon code for an extra 20% on orders above ₹500, plus 10% off via bank credit cards.",
    code: 'EXTRA20',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-13',
    badge: 'FLAT 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'BIRKENSTOCK',
    title: 'Flat 10% OFF on Birkenstock Products at Nykaa — Prepaid Orders Only',
    description: 'Shop Birkenstock on Nykaa and save flat 10% — apply the coupon code at checkout, valid on prepaid orders only.',
    code: 'BIRKEN10',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-14',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'FIRST ORDER',
    title: 'New Nykaa App Users — Up to 50% OFF + Extra 10% on First Purchase',
    description: 'First-time Nykaa app shoppers save up to 50% on select brands — apply the coupon code for an extra flat 10% off, up to ₹500 maximum discount.',
    code: 'NEW10',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-15',
    badge: 'FREE SHIPPING',
    badgeType: 'FREE',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'SITEWIDE',
    title: 'Free Shipping on All Nykaa Orders Above ₹299',
    description: 'Shop sitewide on Nykaa and enjoy free delivery on orders above ₹299 — covers all major brands with no coupon code required.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-16',
    badge: 'EXTRA 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'CAMPUS',
    title: 'Save Extra 10% OFF on Campus Products at Nykaa — Prepaid Orders Only',
    description: 'Shop Campus products on Nykaa and save an extra 10% — apply the coupon code at checkout on prepaid orders for this limited-time saving.',
    code: 'CAMPUS10EXTRA',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-17',
    badge: 'UP TO 20% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'THE ORDINARY',
    title: 'Shop The Ordinary on Nykaa — Up to 20% OFF + Extra 5% with Coupon',
    description: 'Save up to 20% on The Ordinary skincare products on Nykaa — apply the coupon code for an extra 5% off on eligible products.',
    code: 'ORDINARYNEW',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-18',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'FOXTALE',
    title: 'Foxtale Flash Deal on Nykaa — Up to 40% OFF Across All Categories',
    description: "Shop the Foxtale range on Nykaa at up to 40% off — covers skin, men's store, bath & body, makeup, fragrance, and more from ₹174.",
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-19',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'BATH & BODY',
    title: 'Nykaa Bath & Body Sale — Up to 60% OFF + Extra 10% via HSBC Cards',
    description: "Save up to 60% on Nykaa's bath and body range — extra 10% off available via HSBC credit cards, covering bath, body care, grooming, and more.",
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-20',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'WELLNESS',
    title: 'Nykaa Health & Wellness Sale — Up to 50% OFF Across All Categories',
    description: "Shop Nykaa's health and wellness range at up to 50% off — covers skin, hair, and health supplements, sports nutrition, weight management, and more.",
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-21',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FC2779]',
    color: '#FC2779',
    type: 'FRAGRANCES',
    title: "Nykaa Fragrance Sale — Up to 60% OFF on Women's & Men's Perfumes",
    description: "Discover Nykaa's fragrance collection at up to 60% off — covers women's and men's fragrances, aromatherapy, and fragrance kits starting from ₹299.",
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-22',
    badge: 'UP TO 70% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2D0A1F]',
    color: '#2D0A1F',
    type: 'BODY CARE',
    title: 'Nykaa Premium Body Care — Up to 70% OFF on Blockbuster Picks',
    description: "Shop Nykaa's premium body care blockbuster deals and save up to 70% — no coupon code needed, discount pre-applied on eligible products.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  }
];

