// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const LEVIS_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'NEW ARRIVALS',
    title: 'Get up to 60% off on New Arrivals',
    description: 'Explore the newest denim styles and apparel drops at up to 60% OFF.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-2',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'JACKETS',
    title: 'Men\'s Jackets | Up to 60% OFF',
    description: 'Save up to 60% on men\'s jackets from Levi\'s.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-3',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'JACKETS',
    title: 'Women\'s Jacket Collection | Up to 60% OFF',
    description: 'Save up to 60% on women\'s jackets. Styles covered: Bomber, Denim, Standard, Tailored, and Trucker.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-4',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'MENSWEAR',
    title: 'Men\'s Wear Collection | Up to 60% OFF',
    description: 'Save up to 60% on men\'s wear. Covers top wear, bottoms, jackets, and more.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-5',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'WOMENSWEAR',
    title: 'Women\'s Wear Collection | Up to 60% OFF',
    description: 'Save up to 60% on women\'s wear. Prices start from Rs 499 and above.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-6',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'BOTTOMS',
    title: 'Cargo Pants | Up to 60% OFF',
    description: 'Save up to 60% on cargo pants.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-7',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'JEANS',
    title: 'Jeans | 40% to 60% OFF',
    description: 'Save between 40% and 60% on a wide range of jeans for men and women. Covers multiple fits, washes, and denim styles.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-8',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'JEANS',
    title: 'Get up to 50% off on Men\'s Jeans',
    description: 'Shop the latest collection of men\'s denim jeans and enjoy up to 50% OFF sitewide.',
    code: 'LEVIS50',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-9',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'SITEWIDE',
    title: 'Sitewide Sale | Up to 50% OFF',
    description: 'Save up to 50% across all products on the Levi\'s store.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-10',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'BOTTOMS',
    title: 'Men\'s Shorts | Up to 50% OFF',
    description: 'Save up to 50% on men\'s shorts with no coupon code required.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-11',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'WOMENSWEAR',
    title: 'Women\'s Jumpsuits | Up to 50% OFF',
    description: 'Save up to 50% on women\'s jumpsuits.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-12',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'TOPS',
    title: 'Women\'s T-Shirts | Up to 50% OFF',
    description: 'Save up to 50% on women\'s T-shirts. Prices start from Rs 499.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-13',
    badge: 'UP TO 45% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'JEANS',
    title: 'Get up to 45% off on Women\'s Jeans',
    description: 'Shop skinny, straight, and mom-fit jeans for women at up to 45% OFF.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-14',
    badge: 'UP TO 45% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'FOOTWEAR',
    title: 'Footwear | Up to 45% OFF',
    description: 'Save up to 45% on footwear including sneakers, slides, flip-flops, and more.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-15',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'T-SHIRTS',
    title: 'Get up to 40% off on T-Shirts & Casual Wear',
    description: 'Shop graphic tees, polos, and casual t-shirts online at up to 40% OFF.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-16',
    badge: 'UP TO 35% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'JACKETS',
    title: 'Get up to 35% off on Winter Jackets & Outerwear',
    description: 'Shop the winter outerwear collection including hoodies and jackets at up to 35% OFF.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-17',
    badge: 'FLAT ₹500 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'SITEWIDE',
    title: 'Flat Rs 500 OFF on Orders Above Rs 2,500',
    description: 'Save a flat Rs 500 on your order from the latest new arrivals collection with minimum transaction value of Rs 2,500.',
    code: 'LEVIIAFF500',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-18',
    badge: 'FLAT 30% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'JACKETS',
    title: 'Flat 30% off on Denim & Trucker Jackets',
    description: 'Get a flat 30% discount on the trucker and denim jacket collection for men and women.',
    code: 'LEVISJKT30',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-19',
    badge: 'FLAT 20% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'SITEWIDE',
    title: 'Flat 20% off on Sitewide Orders',
    description: 'Use this code on your entire order across jeans, jackets, t-shirts and accessories.',
    code: 'LEVISEXTRA20',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-20',
    badge: 'FLAT 15% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'APP EXCLUSIVE',
    title: 'App Exclusive | Flat 15% OFF on All Orders',
    description: 'Save a flat 15% on your order through the Levi\'s app. Minimum cart value of Rs 3,499 required.',
    code: 'APP15',
    verified: 'Verified',
    userType: 'App Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-21',
    badge: '15% OFF',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'ACCESSORIES',
    title: 'Get 15% off on Belts, Caps & Accessories',
    description: 'Add belts, caps, bags, and other accessories to your order and save 15%.',
    code: 'LEVISACC15',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-22',
    badge: 'EXTRA 10% OFF',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'NEW ARRIVALS',
    title: 'New Arrivals | Extra 10% OFF on 500+ Styles',
    description: 'Shop from over 500 new styles across jeans, T-shirts, shirts, and jackets. Use the code at checkout for an extra 10% off.',
    code: 'NEW10',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-23',
    badge: 'EXTRA 10% OFF',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'SITEWIDE',
    title: 'Extra 10% OFF on Orders Above Rs 3,299',
    description: 'Save an extra 10% on your order. Minimum cart value of Rs 3,299 required.',
    code: 'SAVEMORE10',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-24',
    badge: 'FLAT 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'SITEWIDE',
    title: 'Extra 10% OFF Sitewide',
    description: 'Save a flat 10% on all orders sitewide using the code at checkout.',
    code: 'NEW10',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-25',
    badge: 'FREE SHIPPING',
    badgeType: 'FREE',
    badgeColor: 'bg-[#BB1E3C]',
    color: '#BB1E3C',
    type: 'SITEWIDE',
    title: 'Get Free Shipping on Your Order',
    description: 'Enjoy free standard shipping on qualifying Levi\'s orders, no minimum spend required.',
    code: 'LEVISFREESHIP',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-26',
    badge: 'FREE SHIPPING',
    badgeType: 'FREE',
    badgeColor: 'bg-[#2C3E5C]',
    color: '#2C3E5C',
    type: 'SHIPPING',
    title: 'Free Shipping on All Orders',
    description: 'Free delivery on all orders — no minimum cart value required. Delivery across India within 5 to 7 days.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  }
];
