// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'CASHBACK';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const ZEPTO_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO 95% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'SITEWIDE',
    title: 'Sitewide: Up to 95% OFF + Extra ₹200 OFF on Orders Above ₹1,299',
    description: 'Shop electronics, fashion, kitchen products, and more — save up to 95% sitewide plus an extra ₹200 off on orders above ₹1,299. Install the app for additional benefits.',
    code: 'QUICKSAVE200',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-2',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'GROCERY',
    title: 'Deals of the Day: Up to 60% OFF + Extra ₹100 OFF',
    description: 'Save up to 60% on groceries and essentials today — plus an extra ₹100 off when you apply the deal code. Limited-time offer.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-3',
    badge: '₹25 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'WALLET',
    title: 'Amazon Pay Offer: ₹25 Cashback on Orders',
    description: 'Pay with Amazon Pay on Zepto and earn ₹25 cashback on your order.',
    code: 'AMAZONPAY',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-4',
    badge: 'UP TO ₹50 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'UPI',
    title: 'MobiKwik UPI: Up to ₹50 Cashback on Orders Above ₹399',
    description: 'Pay via MobiKwik UPI on Zepto and earn up to ₹50 cashback on orders above ₹399.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-5',
    badge: 'UP TO ₹100 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'REWARDS',
    title: 'Assured Cashback Up to ₹100 on Orders Above ₹399',
    description: 'Shop on Zepto and get up to ₹100 assured cashback on orders above ₹399 — applicable twice per user.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-6',
    badge: 'FLAT ₹50 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'UPI',
    title: 'Flat ₹50 Cashback via BHIM App',
    description: 'Pay via the BHIM app on Zepto and get ₹50 cashback — valid once per user.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-7',
    badge: 'UP TO ₹300 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'WALLET',
    title: 'MobiKwik Offer: Up to ₹300 Cashback on All Orders',
    description: 'Order on Zepto and earn up to ₹300 cashback with MobiKwik — valid for all users on orders above ₹399.',
    code: 'MBK300',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-8',
    badge: 'FLAT ₹75 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'BANK OFFER',
    title: 'Flat ₹75 OFF with VISA Classic Debit Cards',
    description: 'Pay with your VISA Classic debit card on Zepto and save ₹75 on orders above ₹500.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-9',
    badge: 'FLAT 40% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'ZEPTO CAFE',
    title: 'Zepto Cafe: Flat 40% OFF on First Order',
    description: 'New to Zepto Cafe? Save 40% on your first order — no minimum value needed. Includes Chocolate Mousse, Veg Puff, Spanish Coffee, Plain Maggie, and more.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-10',
    badge: 'FLAT ₹75 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'BANK OFFER',
    title: 'Flat ₹75 OFF with VISA Platinum Debit Cards',
    description: 'Pay with your VISA Platinum debit card on Zepto and get a flat ₹75 off on your order.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-11',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'ZEPTO CAFE',
    title: 'Zepto Cafe: Up to 40% OFF on Desi Snacks from ₹49',
    description: 'Save up to 40% on desi snacks at Zepto Cafe — egg, veg, and non-veg options starting from just ₹49.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-12',
    badge: 'UP TO ₹50 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'UPI',
    title: 'Up to ₹50 Cashback via BHIM App on Orders Above ₹99',
    description: 'Pay via the BHIM app on Zepto and earn up to ₹50 instant cashback on orders above ₹99.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-13',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'ZEPTO CAFE',
    title: 'Zepto Cafe: Up to 40% OFF on Desserts from ₹41',
    description: 'Satisfy your sweet tooth with up to 40% off on Zepto Cafe desserts — Kesari Rasmalai, Chocolate Mousse, Mango Pastry Jar, Moong Dal Halwa, and more from ₹41.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-14',
    badge: 'UP TO 30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'ZEPTO CAFE',
    title: 'Zepto Cafe: Up to 30% OFF on Meals from ₹69',
    description: 'Order hearty meals at Zepto Cafe and save up to 30% — Paneer Makhani & Rice, Margherita Pizza, Chicken Meatball Pizza, Garlic Pesto Pizza, and more from ₹69.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-15',
    badge: 'UP TO 80% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'FRUITS & VEGETABLES',
    title: 'Fruits & Vegetables: Up to 80% OFF',
    description: 'Stock up on fresh fruits and vegetables at up to 80% off — limited-period offer for all users.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-16',
    badge: 'FLAT ₹100 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'BANK OFFER',
    title: 'Flat ₹100 OFF with HSBC Bank Credit Cards on Orders Above ₹999',
    description: 'Pay with your HSBC Bank Credit Card on Zepto and save 12% flat on orders above ₹999.',
    code: 'ZEPHSBC',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-17',
    badge: 'UP TO 80% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'ELECTRONICS',
    title: 'Electronics & Appliances: Up to 80% OFF',
    description: 'Shop electronics and appliances on Zepto and save up to 80% — minimum cart value of ₹549 required.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-18',
    badge: 'UP TO 79% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'TOYS & SPORTS',
    title: 'Toys & Sports Store: Up to 79% OFF from ₹99',
    description: 'Save up to 79% on toys and sports products starting at just ₹99 — available exclusively on the Zepto app.',
    code: '',
    verified: 'Verified',
    userType: 'App Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-19',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'HOME ESSENTIALS',
    title: 'Home Essentials: Up to 60% OFF',
    description: 'Save up to 60% on home essentials — bedroom, bathroom, home, and kitchen products available.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-20',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'CLEANING',
    title: 'Household Cleaning Products: Up to 60% OFF',
    description: 'Stock up on everyday household cleaning essentials at up to 60% off — toilet cleaner, bathroom cleaner, and more.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-21',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'KITCHEN',
    title: 'Kitchen Accessories: Up to 60% OFF',
    description: 'Save up to 60% on kitchen accessories — kitchen tools, storage, bottles & flasks, cookware, drinkware & bar essentials.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-22',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'STATIONERY',
    title: 'Stationery & Craft Items: Up to 50% OFF from ₹14',
    description: 'Save up to 50% on stationery and craft supplies on Zepto — prices starting from just ₹14.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-23',
    badge: 'ZERO FEE',
    badgeType: 'FREE',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'ESSENTIALS',
    title: 'Zero Convenience Fee on Cigarette Orders',
    description: 'Order cigarettes on Zepto with no convenience fee — quick doorstep delivery in minutes on select orders.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-24',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'HEALTH',
    title: 'Protein Dose Products: Up to 50% OFF',
    description: 'Save up to 50% on protein and health supplements on Zepto — check the app for the full range.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-25',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'PERSONAL CARE',
    title: 'Personal & Hygiene Products: Up to 50% OFF',
    description: 'Save up to 50% on personal care and hygiene essentials on Zepto — check the app for the full range.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-26',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'SKINCARE',
    title: 'Skin Care Essentials: Up to 50% OFF',
    description: 'Save up to 50% on skincare essentials on Zepto — check the app for the full product range.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-27',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'PET CARE',
    title: 'Pet Fest: Up to 40% OFF on Pet Foods from ₹31',
    description: 'Save up to 40% on pet food and accessories — pet food, bowls, cutters, puppy brushes, and more from just ₹31.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-28',
    badge: 'UP TO 30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'BABY CARE',
    title: 'The Baby Store: Up to 30% OFF',
    description: 'Save up to 30% on baby care products — skincare, oral care, diapers, and more. Limited-time offer.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-29',
    badge: 'UP TO 20% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8A2BE2]',
    color: '#8A2BE2',
    type: 'PERSONAL CARE',
    title: 'Freshness Products: Up to 20% OFF',
    description: 'Save up to 20% on freshness and personal care products on Zepto — check the app for the full range.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-30',
    badge: 'UP TO 20% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'DESSERTS',
    title: 'Ice Cream Corner: Up to 20% OFF from ₹84',
    description: 'Cool down with up to 20% off on ice creams — prices starting from ₹84, no code required.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  }
];
