// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'CASHBACK';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const BLINKIT_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'GROCERY',
    title: 'Get up to 40% off on grocery essentials',
    description: 'Shop staples, packaged foods & everyday grocery items and save up to 40% on your order.',
    code: 'BLINKIT40',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-2',
    badge: 'FLAT ₹125 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'FIRST ORDER',
    title: 'Flat ₹125 off on your first Blinkit order',
    description: 'New to Blinkit? Get a flat ₹125 discount on your first order with this welcome offer.',
    code: 'BLINKITNEW',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-3',
    badge: 'UP TO 30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'FRUITS & VEGETABLES',
    title: 'Get up to 30% off on fresh fruits & vegetables',
    description: 'Order farm-fresh fruits and vegetables and enjoy up to 30% off on your basket.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-4',
    badge: 'FREE DELIVERY',
    badgeType: 'FREE',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'DAILY ESSENTIALS',
    title: 'Free delivery on daily essentials orders',
    description: 'Get free delivery when you order daily essentials above the minimum basket value.',
    code: 'FREESHIP',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-5',
    badge: 'UP TO 25% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'DAIRY & BREAKFAST',
    title: 'Get up to 25% off on dairy & breakfast items',
    description: 'Stock up on milk, bread, eggs and breakfast picks at up to 25% off.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-6',
    badge: '15% OFF',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'APP EXCLUSIVE',
    title: 'Extra 15% off on app-exclusive deals',
    description: 'Unlock an additional 15% off on select items when you order through the Blinkit app.',
    code: 'APP15',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-7',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'SNACKS & BEVERAGES',
    title: 'Get up to 50% off on snacks & beverages',
    description: 'Grab your favourite snacks, chips, and beverages at up to 50% off.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-8',
    badge: 'FLAT ₹75 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'PERSONAL CARE',
    title: 'Flat ₹75 off on personal care products',
    description: 'Save a flat ₹75 on personal care and hygiene essentials on eligible orders.',
    code: 'CARE75',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-9',
    badge: 'UP TO 35% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'HOUSEHOLD ESSENTIALS',
    title: 'Get up to 35% off on household essentials',
    description: 'Shop cleaning supplies and household essentials and save up to 35% instantly.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-10',
    badge: 'UP TO 80% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'SITEWIDE',
    title: 'Sitewide: Up to 80% OFF + Rs 200 Paytm Cashback',
    description: 'Shop groceries and staples — rice & flour, edible oils, ghee, spices, salt, sugar, dry fruits, nuts & pulses — and save up to 80%. Pay using the code to get an extra cashback of up to Rs 200 on top of your existing discount. Minimum order value of Rs 199 applies. Pricing starts from Rs 10.',
    code: 'PAYTMUPI',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-11',
    badge: 'UP TO 55% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'FRUITS & VEGETABLES',
    title: 'Fresh Fruits & Vegetables: Up to 55% OFF',
    description: 'Save up to 50% on fresh produce across fruits and vegetables. Enter the code at checkout for an extra 5% off over and above the existing discount. Covers Fresh Vegetables, Fresh Fruits, Mangoes & Melons, Seasonal, and Exotics. Code is valid only for Yes Bank card users.',
    code: 'AUCC30',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-12',
    badge: 'UP TO ₹50 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'UPI',
    title: 'BHIM Card: Up to Rs 50 Cashback',
    description: 'Pay using a RuPay Credit Card on UPI through the BHIM app and save up to Rs 50. Minimum cart value of Rs 599 required. Not applicable on gold & silver coins, gift cards, tobacco, cigarettes, and baby needs products.',
    code: 'BHIMRUPAYCC',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-13',
    badge: 'UP TO 65% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'BABY CARE',
    title: 'Baby Care: Up to 65% OFF (Pampers, MamyPoko & More)',
    description: 'Save up to 20% on Himalaya Baby Care products — baby powder, baby lotion, baby wash, and more. Baby essentials from trusted brands at reduced prices starting from Rs 72.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-14',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'ESSENTIALS',
    title: 'Pooja Essentials: Up to 50% OFF',
    description: 'Save up to 50% on a range of pooja essentials including Deepam pooja oil, camphor, ghee, and more. Prices start from Rs 10.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-15',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'BAKERY',
    title: 'Bakery & Biscuits: Up to 50% OFF',
    description: 'Save up to 20% on Oreo Biscuits including the chocolate flavour variant. Limited time offer.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-16',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'PET CARE',
    title: 'Pet Care: Up to 50% OFF',
    description: 'Save up to 50% on pet care products covering food and grooming accessories for dogs and cats.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-17',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'DESSERTS',
    title: 'Ice Cream & Frozen Desserts: Up to 50% OFF',
    description: 'Save up to 50% on ice creams from brands including Baskin-Robbins, Kwality Walls, and Amul. Free shipping available.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-18',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'SNACKS & BEVERAGES',
    title: 'Snacks & Munchies: Up to 50% OFF',
    description: 'Save up to 30% on snacks and munchies with prices starting from Rs 42.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-19',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'ESSENTIALS',
    title: 'Paan Corner: Up to 50% OFF',
    description: 'Save up to 50% on Paan Corner products with prices starting from Rs 10.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-20',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'GROCERY',
    title: 'Organic & Healthy Living: Up to 40% OFF',
    description: 'Save up to 40% on organic and healthy living products with prices starting from Rs 51.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-21',
    badge: 'UP TO 35% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SNACKS & BEVERAGES',
    title: 'Candies & Gums: Up to 35% OFF',
    description: 'Save up to 35% on candies and gums with prices starting from Rs 45.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-22',
    badge: 'UP TO 35% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'PERSONAL CARE',
    title: 'Personal Care: Up to 35% Instant Discount',
    description: 'Get an instant discount of up to 35% on personal care products. Pricing starts from Rs 38.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-23',
    badge: 'UP TO ₹100 CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'WALLET',
    title: 'Paytm Cashback: Up to Rs 100 on Orders',
    description: 'Pay via Paytm and receive cashback of up to Rs 100 on your order. Minimum transaction value of Rs 750 required. Can be used twice per customer.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-24',
    badge: 'FLAT 25% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'FIRST ORDER',
    title: 'App Download Offer: 25% OFF on First Order',
    description: 'Download the Blinkit app and save 25% on your first order. App-exclusive offer.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-25',
    badge: 'UP TO 20% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'DAIRY & BREAKFAST',
    title: 'Breakfast & Dairy: Up to 20% OFF',
    description: 'Save up to 20% on Bread & Eggs, Paneer, Curd, Cereals, and more. Covers top brands including Amul, Kissan, and Nescafe.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-26',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'DESSERTS',
    title: 'Sweet Tooth: Up to 50% OFF',
    description: 'Save up to 50% on sweet treat products with pricing starting from Rs 20.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-27',
    badge: 'FLAT 5% CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'WALLET',
    title: 'HDFC PayZapp: Flat 5% Cashback on All Orders',
    description: 'Pay via HDFC PayZapp wallet and earn a flat 5% cashback on minimum cart value of Rs 500. Can be used twice per user during campaign period (App only).',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-28',
    badge: 'FLAT 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#F8CB46]',
    color: '#F8CB46',
    type: 'BANK OFFER',
    title: 'Axis Bank Card: 10% OFF',
    description: 'Save 10% when you pay using your Axis Bank card. Additional discount available on website.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-29',
    badge: 'FREE DELIVERY',
    badgeType: 'FREE',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SITEWIDE',
    title: 'Free Delivery on Orders Above Rs 199',
    description: 'Free shipping on all orders crossing the minimum cart value of Rs 199. Applicable on all products.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  }
];
