// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'CASHBACK';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const UBER_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#5B4FBE]',
    color: '#5B4FBE',
    type: 'RIDES',
    title: 'Get Up to 50% Off on Your Next Uber Ride',
    description: 'Save on UberGo, Premier, and Auto rides across your city with this limited-time ride discount.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-2',
    badge: 'FLAT ₹100 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FF5722]',
    color: '#FF5722',
    type: 'FIRST RIDE',
    title: 'Flat ₹100 Off on Your First Uber Ride',
    description: 'New to Uber? Get a flat discount on your first ride booked through the Uber app.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-3',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#4A3AFF]',
    color: '#0D9488',
    type: 'UBER EATS',
    title: 'Up to 40% Off on Uber Eats Food Orders',
    description: 'Order from your favorite restaurants and get up to 40% off on select Uber Eats orders.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-4',
    badge: 'UP TO 30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'AUTO & MOTO',
    title: 'Up to 30% Off on Uber Auto & Uber Moto Rides',
    description: 'Budget-friendly commutes with discounts on Uber Auto and Uber Moto rides in select cities.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-5',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'FIRST 3 RIDES',
    title: 'Flat 50% Off on First 3 Uber Rides | Up to ₹100 Per Ride',
    description: '50% off on your first 3 ride bookings, up to ₹100 per ride.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-6',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF9900]',
    color: '#FF9900',
    type: 'UBER AUTO',
    title: 'Uber Auto: Flat 50% Off on First 3 Auto Bookings',
    description: 'Flat 50% off on your first 3 Uber Auto bookings, up to ₹100 per ride.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-7',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#222222]',
    color: '#222222',
    type: 'UBER MOTO',
    title: 'Uber Moto: Flat 50% Off on First 3 Bike Rides',
    description: 'Flat 50% off on Uber Moto — one of the most affordable ride options across metro cities. Valid on your first 3 bookings, up to ₹100 per ride.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-8',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#008080]',
    color: '#008080',
    type: 'SOUTH INDIA',
    title: 'South India City Deals: Flat 50% Off in Hyderabad, Bengaluru & Chennai',
    description: 'Flat 50% off on rides across Hyderabad, Bengaluru, and Chennai — valid on the first 3 bookings for new users.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-9',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#800080]',
    color: '#800080',
    type: 'WEST INDIA',
    title: 'Mumbai, Pune & Ahmedabad: Flat 50% Off on Cabs, Auto & Bike Bookings',
    description: 'Flat 50% off on cab, auto, and bike ride bookings across Mumbai, Pune, and Ahmedabad — valid on the first 3 rides.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-10',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#4169E1]',
    color: '#4169E1',
    type: 'CAB BOOKINGS',
    title: 'Jaipur, Pune & Ahmedabad: Flat 50% Off on Cab Bookings',
    description: 'Flat 50% off on cab bookings across Jaipur, Pune, and Ahmedabad — up to ₹100 per ride on your first 3 bookings.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-11',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#B22222]',
    color: '#B22222',
    type: 'EAST INDIA',
    title: 'East India: Flat 50% Off in Kolkata, Bhubaneswar, Patna & Ranchi',
    description: 'Flat 50% off on Uber cab bookings across Kolkata, Bhubaneswar, Patna, and Ranchi — up to ₹100 savings per ride.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-12',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#2E8B57]',
    color: '#2E8B57',
    type: 'CENTRAL INDIA',
    title: 'Indore, Bhopal, Raipur & Nagpur: Flat 50% Off on First 3 Rides',
    description: 'Flat 50% off on your first 3 rides across Indore, Bhopal, Raipur, and Nagpur — up to ₹100 per ride.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-13',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#D2691E]',
    color: '#D2691E',
    type: 'NORTH INDIA',
    title: 'Delhi, Chandigarh, Jaipur & Lucknow: Flat 50% Off on Cab Bookings',
    description: 'Flat 50% off on cab bookings across Delhi, Chandigarh, Jaipur, and Lucknow — save up to ₹100 per ride on your first 3 trips.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-14',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#4682B4]',
    color: '#4682B4',
    type: 'UBERGO',
    title: 'UberGo AC Cabs: Flat 50% Off | From ₹100',
    description: 'Flat 50% off on UberGo AC cab bookings. Fares start from ₹100.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-15',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#708090]',
    color: '#708090',
    type: 'ECONOMY CABS',
    title: 'Economy Cabs & Auto: Flat 50% Off on First 3 Rides',
    description: 'Flat 50% off on economy cab and auto bookings across Go Priority, Premier AC, and Auto Priority service types.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-16',
    badge: '14% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000080]',
    color: '#000080',
    type: 'INTERCITY',
    title: 'Intercity Cabs: 14% Off | Save Up to ₹2,000',
    description: '14% off on intercity cab bookings — one of the better savings on longer-distance trips via Uber.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-17',
    badge: '25% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#8B4513]',
    color: '#8B4513',
    type: 'PARCEL',
    title: 'First Parcel Booking: 25% Off on Bike Delivery',
    description: "25% off on your first parcel delivery booking via Uber's bike delivery service.",
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-18',
    badge: '30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#556B2F]',
    color: '#556B2F',
    type: 'UBER RESERVE',
    title: 'Uber Reserve: 30% Off on Scheduled Rides | Up to ₹150',
    description: '30% off on Uber Reserve bookings — schedule your ride up to 90 days in advance and get up to ₹150 off, with 5 minutes of free wait time on arrival.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-19',
    badge: '25% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#DAA520]',
    color: '#DAA520',
    type: 'BUS BOOKINGS',
    title: 'First Intercity Bus Booking: 25% Off | Up to ₹200',
    description: '25% off on your first intercity bus booking via Uber, up to ₹200 — applied automatically at checkout.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-20',
    badge: '25% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#CD853F]',
    color: '#CD853F',
    type: 'RENTALS',
    title: 'Uber Rentals: Up to 25% Off on First Rental Trip | From ₹430/Hour',
    description: 'Up to 25% off on your first Uber Rentals booking — Go Rentals, Sedan Rentals, and XL Rentals available from ₹430/hour.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-21',
    badge: '50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#6A5ACD]',
    color: '#6A5ACD',
    type: 'RESERVE',
    title: 'Reserve a Ride: Up to 50% Off on First Booking',
    description: 'Up to 50% off when you reserve an auto, bike, or car in advance — valid on your first booking.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-22',
    badge: '5% CASHBACK',
    badgeType: 'CASHBACK',
    badgeColor: 'bg-[#FF9900]',
    color: '#FF9900',
    type: 'AMAZON PAY',
    title: 'Amazon Pay: 5% Cashback on All Uber Bookings',
    description: '5% cashback on all Uber ride bookings paid via Amazon Pay — exclusive for Amazon Prime members.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-23',
    badge: '₹200 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#E9967A]',
    color: '#E9967A',
    type: 'BUS',
    title: 'Bus Bookings: Up to ₹200 Off on First Booking',
    description: 'Up to ₹200 off on your first intercity bus booking via Uber.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-24',
    badge: '20% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#20B2AA]',
    color: '#20B2AA',
    type: 'PRE-BOOKINGS',
    title: 'Pre-Bookings: Flat 20% Off — Auto-Applied at Checkout',
    description: 'Flat 20% off on all Uber pre-bookings — discount applied automatically at checkout, no promo code needed.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  }
];
