import type { MetadataRoute } from 'next'

const baseUrl = 'https://www.couponscrew.com'

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    { url: `${baseUrl}/`, lastModified: now, changeFrequency: 'daily', priority: 1.0 },
    { url: `${baseUrl}/stores`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/amazon-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/pepperfry-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/myntra-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/flipkart-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/dominos-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/red-bus-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/jiomart-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/puma-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/lenskart-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/hostinger-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/nykaa-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/ajio-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/muscleblaze-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/indigo-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/rapido-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/bookmyshow-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/ola-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/pw-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/zepto-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/blinkit-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/magicpin-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/kreditbee-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/levis-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/zee5-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/uber-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/unidays-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/hm-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/firstcry-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/sonyliv-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/booking-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/adidas-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/flixbus-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/lifestyle-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/nike-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/expedia-coupon-code`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/stores/categories`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/stores/categories/fashion`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/beauty`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/exercise-and-fitness`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/home-and-kitchen`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/clothing-and-accessories`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/electronics`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/food-and-grocery`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/travel`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/education`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/entertainment`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/finance`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/web-hosting`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/health`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/sports`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/software`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/gaming`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/jewellery`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/eyewear`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/stores/categories/furniture`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/festival-offers`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/festival-offers/amazongreatindiansale-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/black-friday-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/childrens-day-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/christmas-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/cyber-monday-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/diwali-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/dusshera-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/flipkartbigbilliondaysale-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/halloween-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/new-year-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/super-saturday-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/thanksgiving-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/festival-offers/veterans-day-offers`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/categories`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/products/categories/electronics`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/categories/home-and-kitchen`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/categories/health`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/categories/beauty`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/categories/sports`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/categories/toys`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/categories/software`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/categories/video-games`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/categories/pet-supplies`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/acnos-bangle-watch-pack-of-2`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/deelmo-mens-mandarin-collar-kurta`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/desidiya-moon-crystal-night-light`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/minimalist-anti-pigmentation-kit`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/products/pulgos-15-in-1-pushup-board`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/deals`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/deals-of-the-day`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/deals-page`, lastModified: now, changeFrequency: 'daily', priority: 0.7 },
    { url: `${baseUrl}/offers`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/blog`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/blog/how-to-save-money-shopping-online-india`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/blog/raksha-bandhan-gift-ideas`, lastModified: new Date('2026-08-24'), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/blog/bigg-boss-season-20-where-to-watch-deals`, lastModified: new Date('2026-09-06'), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/blog/upi-changes-2000-payments-merchants-mdr-2026`, lastModified: new Date('2026-09-20'), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/blog/big-billion-days-vs-amazon-great-indian-festival`, lastModified: new Date('2026-09-25'), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/faqs`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/feedback`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/about-us`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/branding`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/contact`, lastModified: now, changeFrequency: 'monthly', priority: 0.4 },
    { url: `${baseUrl}/privacy-policy`, lastModified: now, changeFrequency: 'monthly', priority: 0.4 },
    { url: `${baseUrl}/terms-conditions`, lastModified: now, changeFrequency: 'monthly', priority: 0.4 },
  ]
}
