// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'BANK OFFER' | 'DEAL';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const SWIGGY_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'FLAT 50% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'DINEOUT',
    title: 'Flat 50% OFF on Dineout + Free Drinks + Extra ₹150 OFF',
    description: 'New users get 50% off on Dineout bookings plus a flat ₹150 off on orders above ₹1,500 — with free drinks included.',
    code: 'DINE150',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-2',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'FOOD DELIVERY',
    title: 'Up to 50% OFF on Orders Above ₹159 (Max ₹100)',
    description: 'Save up to 50% — capped at ₹100 — on select food from popular brands like Faasos, Behrouz Biryani, and Barista.',
    code: 'SWIGGYIT',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-3',
    badge: 'FLAT ₹200 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'FOOD DELIVERY',
    title: 'Flat ₹200 OFF on Orders Above ₹499',
    description: 'Get a flat ₹200 off on orders from select restaurants when you spend ₹499 or more.',
    code: 'CELEBRATIONS',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-4',
    badge: 'UP TO 30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'FOOD DELIVERY',
    title: 'Up to 30% OFF on Orders Above ₹179 (Max ₹75)',
    description: 'Save up to 30% — up to ₹75 — on food orders from select restaurants with a minimum spend of ₹179.',
    code: 'TRYNEW',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-5',
    badge: 'FLAT ₹175 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'FOOD DELIVERY',
    title: 'Flat ₹175 OFF on Orders Above ₹399',
    description: 'Enjoy ₹175 off on your Swiggy order above ₹399 from select restaurants — code usable once every 2 hours.',
    code: 'FLAT175',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-6',
    badge: 'FLAT ₹125 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'FOOD DELIVERY',
    title: 'Flat ₹125 OFF on Orders Above ₹249',
    description: 'Save ₹125 on your next Swiggy order from select restaurants — minimum spend ₹249, usable once every 2 hours.',
    code: 'FLAVORFUL',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-7',
    badge: 'FLAT ₹50 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'FOOD DELIVERY',
    title: 'Flat ₹50 OFF on Orders Above ₹99',
    description: 'Get a flat ₹50 off on any Swiggy order above ₹99 — no code needed.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-8',
    badge: 'FROM ₹99',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'FOOD DELIVERY',
    title: '99 Store: Meals from ₹99 + Free Delivery',
    description: 'Download the Swiggy app and explore the 99 Store — complete meals and breakfast starting at just ₹99, including Masala Dosa, Idly, Veg Maggi, and more.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-9',
    badge: 'FLAT 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'DINEOUT',
    title: 'Flat 10% OFF on Dineout Pre-Bookings',
    description: 'Pre-book your dine-out experience on Swiggy and save a flat 10% — visit the Dineout page for participating restaurants.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-10',
    badge: 'FLAT ₹100 OFF',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'BANK OFFER',
    title: 'Flat ₹100 OFF Using Axis Bank Prepaid & Transit Cards',
    description: 'Pay with your Axis Bank Prepaid or Transit card on Swiggy and get a flat ₹100 off on orders above ₹299.',
    code: 'AXIS100',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-11',
    badge: '25% OFF',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'BANK OFFER',
    title: '25% OFF Up to ₹125 Using Ujjivan SFB Debit Cards',
    description: 'Save 25% up to ₹125 on Swiggy orders above ₹400 when you pay with an Ujjivan Small Finance Bank debit card.',
    code: 'UJJIVAN125',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-12',
    badge: 'FLAT ₹30 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'FOOD DELIVERY',
    title: 'Flat ₹30 OFF on Every Food Order',
    description: 'Get a flat ₹30 off on every Swiggy food order — valid on all orders with no minimum required.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-13',
    badge: 'FLAT ₹50 OFF',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'BANK OFFER',
    title: 'Flat ₹50 OFF Via HDFC PayZapp Card',
    description: 'Pay with your HDFC Bank PayZapp Prepaid card and save ₹50 on orders above ₹349 — plus earn 10X reward points with HDFC Diners Club on orders above ₹300.',
    code: 'PAYZAPP50',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-14',
    badge: '10% OFF',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'BANK OFFER',
    title: '10% OFF Up to ₹150 Using HDFC Bank Credit Cards',
    description: 'Save 10% up to ₹150 on orders above ₹1,250 with select HDFC Bank credit cards — Infinia, Regalia, and Diners Black.',
    code: 'HDFC150',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-15',
    badge: '4% CASHBACK',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'BANK OFFER',
    title: '4% Cashback Via Axis Bank Ace Credit Cards',
    description: 'Pay with your Axis Bank Ace Credit Card on Swiggy and earn 4% cashback — credited by Axis Bank within 30–90 days.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-16',
    badge: '25% OFF',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'BANK OFFER',
    title: 'AU Bank Credit Card: 25% OFF Up to ₹100',
    description: 'Save 25% up to ₹100 on Swiggy orders above ₹299 in select cities — using AU Bank Credit Cards, valid twice per user.',
    code: 'AUCC100',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-17',
    badge: '25% OFF',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'BANK OFFER',
    title: 'AU Bank Card: Flat 25% OFF Up to ₹100',
    description: 'Get 25% off up to ₹100 on Swiggy orders above ₹349 in select cities — valid with AU Bank cards, usable twice per user.',
    code: 'AUBANK100',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-18',
    badge: '4% CASHBACK',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'BANK OFFER',
    title: '4% Cashback Via Flipkart Axis Bank Credit Cards',
    description: 'Earn 4% cashback on Swiggy orders using your Flipkart Axis Bank Credit Card — plus 3X reward points on qualifying transactions.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-19',
    badge: '10X POINTS',
    badgeType: 'BANK OFFER',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'BANK OFFER',
    title: 'Earn 10X Reward Points with HDFC Diners Club Credit Cards',
    description: 'Order on Swiggy via web or app with your HDFC Diners Club Credit Card and earn 10X reward points on orders above ₹300.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-20',
    badge: 'UP TO 30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'FOOD DELIVERY',
    title: 'North Indian Restaurants in Bangalore: Up to 30% OFF',
    description: 'Save up to 30% on North Indian food from top Bangalore restaurants — including Samosa Party, Goli Vada Pav, Anand Sweets, Purani Dilli, and more.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-21',
    badge: 'KFC AT ₹447',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'FOOD DELIVERY',
    title: 'KFC Chick & Share Bucket at ₹447 on Swiggy',
    description: 'Order the KFC Chick & Share Bucket (large popcorn + 3 Pepsi cans) for just ₹447 via Swiggy — or save 43% on KFC\'s Hot & Crispy combo at ₹476.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-22',
    badge: 'UP TO 20% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'DINEOUT',
    title: 'Premium Dining in Mumbai: Up to 20% OFF',
    description: 'Dine at Mumbai\'s top spots and save up to 20% — including Starbucks, Baskin Robbins, NIC Natural Ice Creams, Great Indian Khichdi, and more.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-23',
    badge: 'DELHI DEALS',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#282C3F]',
    color: '#282C3F',
    type: 'FOOD DELIVERY',
    title: 'Burgers & Beverages at Lowest Price — Delhi Users',
    description: 'Delhi users — order crispy burgers, sandwiches, pastas, combos, and more at the lowest prices, including 2 Crispy Veg Supreme Burgers from Burger King starting at ₹59.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-24',
    badge: 'UP TO 33% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FC8019]',
    color: '#FC8019',
    type: 'FOOD DELIVERY',
    title: 'Popular Restaurants in Vizag: Up to 33% OFF',
    description: 'Save up to 33% on food orders from the best restaurants in Visakhapatnam — including Amul Ice Cream, Grand Alpha, Bunnys Family Restaurant, Helapuri Nethi Biryani, and more.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  }
];
