// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'DEAL';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const MUSCLEBLAZE_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'BIRTHDAY SALE',
    title: 'MuscleBlaze Birthday Sale — Up to 50% OFF + Extra 10% with Coupon',
    description: "Shop MuscleBlaze's Birthday Sale and save up to 50% — apply the coupon code at checkout for an extra 10% off on selected products.",
    code: 'BLAZEX',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-2',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'PROTEIN',
    title: 'MuscleBlaze Protein Range — Up to 40% OFF + Extra 10% on Whey & Plant Protein',
    description: "Save up to 40% on MuscleBlaze's protein range — apply the coupon code for an extra 10% off on Raw Whey Isolate, Raw Whey Protein, and more.",
    code: 'PROTEIN',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-3',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'SITEWIDE',
    title: 'MuscleBlaze Sitewide Sale — Up to 50% OFF + Extra 5% on All Categories',
    description: 'Shop across all MuscleBlaze categories and save up to 50% — apply the coupon code for an extra 5% off on proteins, gainers, pre-workout, and more.',
    code: 'MBSITE5',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-4',
    badge: 'FLAT ₹200 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'FIRST ORDER',
    title: 'New to MuscleBlaze? Save Up to 50% + Flat ₹200 OFF on Your First Order',
    description: 'First-time MuscleBlaze shoppers can save up to 50% sitewide and get an additional flat ₹200 off — apply the coupon code on orders of ₹1,999 and above.',
    code: 'MBNEW200',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-5',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'GYM WEAR',
    title: 'MuscleBlaze Gym Wear — Up to 50% OFF + Extra 10% on Orders Above ₹999',
    description: 'Shop MuscleBlaze gym clothes for men and women at up to 50% off — use the coupon code on orders above ₹999 for an extra 10% discount.',
    code: 'MBGYM',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-6',
    badge: 'FROM ₹429',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'TOP SELLERS',
    title: 'MuscleBlaze Top Sellers — Up to 50% OFF + Extra 5% Starting from ₹429',
    description: "Shop MuscleBlaze's best-selling supplements at up to 50% off — apply the coupon code for an extra 5% saving on products starting from just ₹429.",
    code: 'MBSITE5',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-7',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'BIOZYME',
    title: 'Shop MuscleBlaze Biozyme Range — Up to 50% OFF + Extra 5% with Coupon',
    description: 'Save up to 50% on the MuscleBlaze Biozyme range — apply the coupon code for an extra 5% off across Biozyme, Gainers, Creatines, and Fit Foods.',
    code: 'BIOX',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-8',
    badge: 'UP TO 45% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'CREATINE',
    title: 'MuscleBlaze Creatine Monohydrate — Up to 45% OFF + Extra 5% with Coupon',
    description: 'Save up to 45% on MuscleBlaze Creatine Monohydrate products — apply the coupon code to stack an additional 5% off on top.',
    code: 'MBSITE5',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-9',
    badge: 'EXTRA ₹150 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'SPECIAL DEAL',
    title: 'MuscleBlaze Deal — Up to 50% OFF + Extra ₹150 on Orders Above ₹1,999',
    description: 'Shop MuscleBlaze and save up to 50% — use the coupon code for an additional ₹150 off on orders of ₹1,999 or more, valid once per user.',
    code: 'MBEXTRA',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-10',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'AMINO ACIDS',
    title: 'MuscleBlaze Liquid Carnitine & BCAA — Up to 40% OFF + Extra 5% with Coupon',
    description: "Save up to 40% on MuscleBlaze's Liquid Carnitine and BCAA range — apply the coupon code at checkout for an extra 5% off on eligible products.",
    code: 'MBSITE5',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-11',
    badge: 'EXTRA 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'FIRST ORDER',
    title: 'New User Deal — Up to 50% OFF + Extra 10% OFF on First MuscleBlaze Order',
    description: 'First-time MuscleBlaze shoppers get up to 50% off on blockbuster deals — apply the coupon code for an extra 10% off on orders above ₹999.',
    code: 'MBNEW10',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-12',
    badge: 'FREE SHAKER',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'BIOZYME',
    title: 'New MuscleBlaze Users — Extra 5% OFF + Free Shaker with 1kg+ Biozyme Whey',
    description: 'New users buying 1kg or more of MuscleBlaze Biozyme range get an extra 5% off and a free shaker — not valid on Flash Sale or heavily discounted products.',
    code: 'MBSITE5',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-13',
    badge: 'EXTRA 15% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'CREAMP',
    title: 'New Users Save Extra 15% OFF on MuscleBlaze Creatine CreAMP Range',
    description: 'First-time MuscleBlaze shoppers can save an extra 15% on the Creatine CreAMP range — valid on 100g and above, applied via coupon code at checkout.',
    code: 'CREA15',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-14',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'SITEWIDE',
    title: 'MuscleBlaze Sitewide — Up to 50% OFF + Extra 5% Across All Categories',
    description: 'Shop the full MuscleBlaze range and save up to 50% — apply the coupon code for an extra 5% off on proteins, gainers, pre-workout, and more.',
    code: 'CART5',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-15',
    badge: 'EXTRA 5% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'MASS GAINERS',
    title: 'MuscleBlaze Mass Gainer Supplements — Get Extra 5% OFF with Coupon',
    description: 'Shop MuscleBlaze Mass Gainer supplements and save an extra 5% — apply the coupon code at checkout on eligible mass gainer products.',
    code: 'MB5OFF',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-16',
    badge: 'EXTRA 5% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'SUPPLEMENTS',
    title: 'Save Extra 5% OFF on Selected MuscleBlaze Products',
    description: 'Shop selected MuscleBlaze products and save an extra 5% — apply the coupon code at checkout to activate the discount on eligible items.',
    code: 'MB5OFF',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-17',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'PRE-WORKOUT',
    title: 'MuscleBlaze Workout Essentials — Up to 40% OFF + Extra 10% on Pre & Post Workout',
    description: 'Save up to 40% on MuscleBlaze workout essentials — apply the coupon code for an extra 10% off on BCAA, Creatine, Pre/Post Workout, and more.',
    code: 'WORK10',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-18',
    badge: 'EXTRA ₹150 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'BEST DEALS',
    title: 'MuscleBlaze Best Deals — Up to 50% OFF + Extra ₹150 on Orders Above ₹1,999',
    description: 'Shop MuscleBlaze\'s top deals across Biozyme, Gainers, Creatines, and Fit Foods — save up to 50% and get an extra ₹150 off on orders of ₹1,999 and above.',
    code: 'MBEXTRA',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-19',
    badge: 'FLAT 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'FIRST ORDER',
    title: 'New to MuscleBlaze? Get Flat 10% OFF on Your First Order Above ₹999',
    description: 'First-time MuscleBlaze shoppers get a flat 10% off on their first order — apply the coupon code at checkout on orders of ₹999 or more.',
    code: 'MBNEW10',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-20',
    badge: 'EXTRA 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'PRE-WORKOUT',
    title: 'New Users Get Extra 10% OFF on MuscleBlaze Pre-Workout Range',
    description: 'First-time MuscleBlaze shoppers can save an extra 10% on the pre-workout range — apply the coupon code at checkout to activate the discount.',
    code: 'PWNEW',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-21',
    badge: 'EXTRA 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#F26522]',
    color: '#F26522',
    type: 'CREATINE',
    title: 'New Users Save Extra 10% OFF on MuscleBlaze Creatine Monohydrate Range',
    description: 'First-time MuscleBlaze shoppers get an extra 10% off on the full Creatine Monohydrate range — apply the coupon code at checkout to redeem.',
    code: 'CREA10',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  }
];