// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'SPECIAL';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const MAGICPIN_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'SAVE 100%',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'VOUCHERS',
    title: 'Vouchers | Save 100% on Bata, Mamaearth & Wrogn Vouchers',
    description: 'Save 100% on vouchers from Bata, Mamaearth, and Wrogn online stores. No discount code needed.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-2',
    badge: 'UP TO 80% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'BEAUTY',
    title: 'Beauty & Grooming | Up to 80% OFF',
    description: 'Save up to 80% on beauty and grooming products. Available brands include Plum, Boddess, Buywow, Mamaearth, Nykaa, and more.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-3',
    badge: 'UP TO 70% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'DINING OUT',
    title: 'Dine-Out | Up to 70% OFF',
    description: 'Save up to 70% on dine-out orders. Applicable on McDonald\'s, Oven Story, Lunch Box, and other food brands.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-4',
    badge: 'UP TO 65% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'FASHION',
    title: 'Fashion Brands | Up to 65% OFF',
    description: 'Save up to 65% on fashion brands. Available brands include Max, Puma, Peter England, and more.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-5',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'SITEWIDE',
    title: 'Sitewide | Up to 60% OFF on All Products',
    description: 'Save up to 60% across all products on Magicpin covering Grocery, Dine-Out, Beauty, and brands like Myntra, McDonald\'s, Bata, Mamaearth, Boat, and Aurelia.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-6',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'FIRST ORDER',
    title: 'Get up to 50% off + cashback on your first Magicpin order',
    description: 'New to Magicpin? Enjoy up to 50% off plus extra cashback credited to your wallet on your first order.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-7',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'GROCERY DEALS',
    title: 'Grocery Essentials | Up to 50% OFF',
    description: 'Save up to 50% on grocery essentials. Available on Blinkit, Ratnadeep, ITC Store, and more.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-8',
    badge: 'FLAT 50% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'VOUCHERS',
    title: 'Fossil Voucher | 50% OFF',
    description: 'Save a flat 50% on a Fossil voucher — available for Rs 1,000. Use the code at checkout for an additional 5% off on this order.',
    code: 'MAGIC5',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-9',
    badge: 'FLAT 50% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'VOUCHERS',
    title: 'McDonald\'s Voucher | 50% OFF',
    description: 'Save a flat 50% on a McDonald\'s voucher — available for Rs 45. Entitles you to any regular meal on a purchase of Rs 389 (online orders only).',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-10',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'DINING OUT',
    title: 'Up to 40% off on weekend dining at select restaurants',
    description: 'Plan your weekend outing and get up to 40% off the bill at select partner restaurants near you.',
    code: 'WEEKEND40',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-11',
    badge: 'UP TO 35% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'SALON & SPA',
    title: 'Get up to 35% off on premium spa treatments',
    description: 'Relax and unwind with up to 35% off on premium spa treatments booked through Magicpin.',
    code: 'SPA35',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-12',
    badge: 'FLAT 35% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'FOOD & BEVERAGES',
    title: 'Oven Story Pizza | Flat 35% OFF',
    description: 'Save a flat 35% on Oven Story Pizza orders.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-13',
    badge: 'FLAT 32% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'FOOD & BEVERAGES',
    title: 'Cafe Coffee Day | Flat 32% OFF',
    description: 'Save 32% on Cafe Coffee Day orders starting from Rs 750.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-14',
    badge: 'UP TO 30% CASHBACK',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'DINING OUT',
    title: 'Get up to 30% cashback on dining out at partner restaurants',
    description: 'Discover nearby restaurants and enjoy up to 30% cashback when you dine out and pay via the Magicpin app.',
    code: 'MAGIC30',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-15',
    badge: 'UP TO 30% CASHBACK',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'FITNESS',
    title: 'Fitness | Earn Rewards & Cashback on Gym, Yoga & Boxing',
    description: 'Earn up to 30% cashback — up to Rs 1,000 — on bookings at select fitness gyms, yoga studios, and boxing centres. Additional vouchers available on booking.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-16',
    badge: 'UP TO 25% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'GROCERY DEALS',
    title: 'Save up to 25% on grocery & daily essentials nearby',
    description: 'Shop groceries and daily essentials from local stores near you and save up to 25% with Magicpin offers.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-17',
    badge: 'UP TO 25% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'HEALTHCARE',
    title: 'Pharmacy Products | Up to 25% OFF',
    description: 'Save up to 25% on pharmacy products. Applicable on Apollo Pharmacy, Himalaya products, and more.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-18',
    badge: 'FLAT 20% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'SALON & SPA',
    title: 'Flat 20% off on your next salon & spa booking',
    description: 'Book a salon or spa appointment near you and get a flat 20% discount on your total bill.',
    code: 'SALON20',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-19',
    badge: 'UP TO 20% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'GIFT CARDS',
    title: 'Gift Cards | Up to 20% OFF',
    description: 'Save on digital vouchers from Nykaa, Amazon Pay, Myntra, BigBasket, and more. Instant discounts on gift cards and recharges.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-20',
    badge: 'FLAT 15% CASHBACK',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'CASHBACK OFFERS',
    title: 'Flat 15% cashback on nearby store purchases',
    description: 'Discover local stores around you and earn a flat 15% cashback credited straight to your Magicpin wallet.',
    code: 'PIN15',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-21',
    badge: '10% CASHBACK',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'CASHBACK OFFERS',
    title: 'Earn 10% cashback on fashion & lifestyle purchases',
    description: 'Shop fashion and lifestyle products at partner outlets and earn 10% cashback in your Magicpin wallet.',
    code: 'STYLE10',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-22',
    badge: 'UP TO ₹2,000 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'ACCESSORIES',
    title: 'Watches | Up to Rs 2,000 OFF',
    description: 'Save up to Rs 2,000 on watches at Magicpin.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-23',
    badge: 'RS 100 BONUS',
    badgeType: 'FREE',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'FIRST ORDER',
    title: 'New Users | Rs 100 Worth of Magicpoints on Sign Up',
    description: 'Sign up on Magicpin and receive Rs 100 worth of Magicpoints. Valid for new users only.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: 'Limited Period'
  },
  {
    id: 'coupon-24',
    badge: 'FREE DELIVERY',
    badgeType: 'FREE',
    badgeColor: 'bg-[#FF3278]',
    color: '#FF3278',
    type: 'GROCERY DEALS',
    title: 'Free delivery on your next grocery order',
    description: 'Get free delivery on eligible grocery and essentials orders placed through the Magicpin app.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-25',
    badge: 'DEALS FROM ₹9',
    badgeType: 'SPECIAL',
    badgeColor: 'bg-[#1A1A1A]',
    color: '#1A1A1A',
    type: 'FOOD & BEVERAGES',
    title: 'Classic Pizza & Crispy Burger | Starting at Rs 9',
    description: 'Order a Classic Pizza or Crispy Burger with prices starting from Rs 9.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: 'Limited Period'
  }
];
