// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT' | 'DEAL' | 'BOGO';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const LENSKART_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'FREE GIFT',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'MEMBERSHIP',
    title: 'Join Lenskart\'s Hustlr Club from ₹249 — Get Free Hustlr Glasses with Membership',
    description: 'Sign up for the Hustlr Club membership on Lenskart and get a free pair of Hustlr glasses with your plan — membership starts at just ₹249.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-2',
    badge: 'EXTRA 60% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'EYEWEAR',
    title: 'Get Extra 60% OFF on Your 3rd Product at Lenskart',
    description: 'Add three products to your Lenskart cart and save an extra 60% on the third item — apply the coupon code at checkout to activate.',
    code: 'GET60',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-3',
    badge: 'FREE FRAMES',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'CHALLENGE',
    title: 'Walk 20,000 Steps on Lenskart & Redeem Eyeglass Frames Worth Up to ₹2,000',
    description: "Complete Lenskart's 20,000-step walking challenge and unlock eyeglass frames worth up to ₹2,000 as a reward — eligible users only.",
    code: '',
    verified: 'Verified',
    userType: 'Eligible Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-4',
    badge: 'FLAT ₹500 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'FIRST ORDER',
    title: 'New to Lenskart? Get Flat ₹500 OFF on Your First Eyewear Order',
    description: 'First-time shoppers on Lenskart can save flat ₹500 on trendy glasses — no coupon code required, discount applied automatically for new users.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-5',
    badge: 'UP TO 70% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'EYEGLASSES',
    title: 'Lenskart Eyeglasses Sale — Up to 70% OFF on Frames & Lenses',
    description: 'Shop a wide range of eyeglasses and frames on Lenskart at up to 70% off — choose from trendy designs, premium lenses, and top eyewear brands.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-6',
    badge: 'FLAT 15% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'GOLD MEMBER',
    title: 'Lenskart Gold Membership — Flat 15% OFF + Complimentary Lens Solution',
    description: 'Sign up for Lenskart Gold and save flat 15% on your orders — no minimum cart value required, plus a complimentary lens solution included.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-7',
    badge: 'FREE LENSES',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'STORE OFFER',
    title: 'First Visit to Lenskart Store? Claim a Free Lens Replacement',
    description: 'Visit your nearest Lenskart store for the first time and claim a free lens replacement — coupon code sent to your WhatsApp after booking, valid on premium Anti-Glare glasses.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-8',
    badge: 'FRAMES AT ₹1',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'FRAMES',
    title: 'Premium Eyeglass Frames for Just ₹1 at Lenskart — Buy with Lenses',
    description: 'Get stylish eyeglass frames for just ₹1 when you purchase lenses on Lenskart — choose from a wide range of designs for men, women, and kids.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-9',
    badge: '2 FOR ₹5000',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'MELLER',
    title: 'Shop Meller Glasses on Lenskart — Buy Any 2 for ₹5,000',
    description: "Explore Lenskart's Meller collection and buy any two pairs for ₹5,000 — a flat bundle price on stylish designer frames.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-10',
    badge: 'BUY 1 GET 1 FREE',
    badgeType: 'BOGO',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'SUNGLASSES',
    title: 'Buy 1 Get 1 FREE on Trending Sunglasses — 1,500+ Styles at Lenskart',
    description: 'Add two pairs of sunglasses to your Lenskart cart and the lower-priced pair becomes free — covers 1,500+ styles including Vincent Chase and John Jacobs.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-11',
    badge: 'UP TO 40% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'VINCENT CHASE',
    title: 'Vincent Chase Rectangle Sunglasses — Up to 40% OFF from ₹600 at Lenskart',
    description: 'Shop Vincent Chase rectangle glasses on Lenskart at up to 40% off — Gold members also get Buy 1 Get 1 free on eligible styles.',
    code: '',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-12',
    badge: 'EXTRA ₹1000 OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'EYEWEAR',
    title: 'Save an Extra ₹1,000 on a Single Pair of Lenskart Glasses',
    description: 'Buy one pair of glasses on Lenskart and save an extra ₹1,000 with the coupon code — not applicable on Buy 1 Get 1 offers.',
    code: 'SINGLE',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-13',
    badge: 'FLAT 21% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'KIDS EYEWEAR',
    title: 'Kids Eyeglasses at Lenskart — Flat 21% OFF Starting from ₹450',
    description: "Shop kids' eyeglasses on Lenskart and save flat 21% — prices start from ₹450, making quality eyewear affordable for children.",
    code: 'EYECON',
    verified: 'Verified',
    userType: 'Existing Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-14',
    badge: 'FLAT 60% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'JOHN JACOBS',
    title: 'Shop John Jacobs at Lenskart — Flat 60% OFF + Buy 1 Get 1 FREE',
    description: 'Save flat 60% on the John Jacobs eyewear collection at Lenskart — plus get a second pair free on eligible Buy 1 Get 1 offers, starting from ₹1,600.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-15',
    badge: '5% SUPERCASH',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'WALLET OFFER',
    title: 'Pay via MobiKwik on Lenskart — Redeem 5% SuperCash Up to ₹1,000 OFF',
    description: 'Use MobiKwik to pay for your Lenskart order and redeem 5% SuperCash — maximum SuperCash redeemable per order is ₹1,000.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-16',
    badge: 'BUY 1 GET 1 FREE',
    badgeType: 'BOGO',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'GOLD MAX',
    title: 'Lenskart Gold Max — Buy 1 Get 1 FREE on Eyeglasses & Sunglasses',
    description: 'Lenskart Gold Max members get a Buy 1 Get 1 free deal on both eyeglasses and sunglasses — valid for all users on eligible products.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-17',
    badge: 'FLAT 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'CONTACT LENSES',
    title: 'Save 10% on Aqualens Contact Lenses at Lenskart — Starting from ₹60',
    description: 'Shop Aqualens contact lenses on Lenskart and save 10% — prices start from just ₹60, making daily lens wear more affordable.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-18',
    badge: 'FLAT 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'ACCESSORIES',
    title: 'Lenskart Gold Members — Get 10% OFF on Contact Lens Solutions & Accessories',
    description: 'Lenskart Gold members can save 10% on contact lens accessories and solutions — no minimum cart value mentioned, benefit applied with Gold membership.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-19',
    badge: 'FROM ₹500',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'EYEWEAR',
    title: 'Refresh Your Look with Lenskart Eyewear — Styles Starting from ₹500',
    description: 'Discover Lenskart\'s latest eyewear collection with frames, spectacles, and sunglasses starting from just ₹500 — trendy designs across premium and everyday styles.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-20',
    badge: '10% OFF + ₹500',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'BANK OFFER',
    title: 'Pay with American Express at Lenskart — Get 10% OFF + ₹500 Paytm Cashback',
    description: 'Shop on Lenskart using an American Express card and save 10% on your order — pay via Paytm wallet to also earn ₹500 cashback.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-21',
    badge: 'FREE SERVICE',
    badgeType: 'DEAL',
    badgeColor: 'bg-[#18C0A8]',
    color: '#18C0A8',
    type: 'SERVICES',
    title: 'Lenskart Members Get Free Quarterly Cleaning & Repair Services',
    description: 'Sign up on Lenskart and enjoy free quarterly cleaning and repair services on selected products — a valuable perk for regular eyewear users.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  },
  {
    id: 'coupon-22',
    badge: 'UP TO 78% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000042]',
    color: '#000042',
    type: 'CONTACT LENSES',
    title: 'Contact Lenses at Lenskart — Up to 78% OFF from ₹99 with Free Shipping',
    description: 'Shop contact lenses on Lenskart at up to 78% off with prices starting from just ₹99 — free shipping included on all contact lens orders.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '31 Aug 2026'
  }
];
