// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const CROCS_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'SAVE 60%',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FF5722]',
    color: '#FF5722',
    type: 'JIBBITZ CHARMS',
    title: 'Crocs Coupon Code – Save 60% on Hashtag Jibbitz',
    description: 'Buy the Hashtag Jibbitz for just ₹160, down from ₹399.\nEnjoy a massive 60% OFF on this Crocs accessory.\nBuy 5 Jibbitz for ₹599 for extra value.\nPerfect for personalizing your Crocs.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-2',
    badge: 'SAVE 50%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'FESTIVE COLLECTION',
    title: 'Crocs Coupon Code – Get Up to 50% Off Festive Collection',
    description: "Shop Crocs' Festive Collection with discounts of up to 50% OFF.\nFind stylish clogs, sandals, flips, and accessories.\nApply code PREPAID5 and save an additional 5% when you pay online.\nLimited-time festive sale.",
    code: 'PREPAID5',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-3',
    badge: 'SAVE 45%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'KIDS CROCS',
    title: 'Crocs Discount Code – Save 45% on Toddler Crocband Cruiser Sandal',
    description: "Get the Toddler Crocband Cruiser Sandal for ₹1,922 instead of ₹3,495.\nEnjoy 45% OFF on this kids' footwear.\nPay upfront online and get 5% knocked off your bill.\nLightweight and comfortable for toddlers.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-4',
    badge: 'SAVE 45%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'KIDS CROCS',
    title: "Crocs Discount Code – Save 45% on Kids' Crocband Cruiser Sandal",
    description: "Buy the Kids' Crocband Cruiser Sandal for ₹2,197 instead of ₹3,995.\nSave 45% instantly.\nEligible for an extra 5% prepaid discount.\nDesigned for everyday comfort and play.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-5',
    badge: 'SAVE 45%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'TODDLER CROCS',
    title: 'Crocs Promo Code – Save 45% on Toddler Crocband Clog',
    description: 'Grab the Toddler Crocband Clog for ₹2,197.\nEnjoy 45% OFF from the original price of ₹3,995.\nGet an extra 5% OFF on prepaid payments.\nLightweight and easy to wear.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-6',
    badge: 'SAVE 40%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'CLASSIC CLOGS',
    title: 'Crocs Promo Code – Save 40% on InMotion Marbled Clog',
    description: 'Buy the InMotion Marbled Clog for ₹4,797 instead of ₹7,995.\nSave 40% instantly.\nChoose online payment to unlock a bonus 5% discount.\nStylish marbled design with superior comfort.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-7',
    badge: 'SAVE 40%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'WOMEN FOOTWEAR',
    title: "Crocs Voucher – Save 40% on Women's InMotion Heel Block Pacer",
    description: "Get the Women's InMotion Heel Block Pacer for ₹5,097.\nEnjoy 40% OFF from ₹8,495.\nExtra 5% prepaid discount available.\nIdeal for all-day comfort and style.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-8',
    badge: 'SAVE 40%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'ECHO CLOG',
    title: 'Crocs Voucher – Save 40% on Echo Clog',
    description: 'Buy the Echo Clog for ₹4,197 instead of ₹6,995.\nSave 40% on this popular Crocs clog.\nEnjoy an extra 5% OFF with prepaid payment.\nDesigned for everyday comfort.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-9',
    badge: 'SAVE 40%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'SANDALS',
    title: 'Crocs Offers – Save 40% on Brooklyn Buckle Low',
    description: 'Get the Brooklyn Buckle Low for ₹3,297 instead of ₹5,495.\nEnjoy 40% OFF instantly.\nExtra 5% OFF on prepaid orders.\nStylish and lightweight everyday footwear.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-10',
    badge: 'SAVE 40%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'FLIP-FLOPS',
    title: 'Crocs Offers – Save 40% on Getaway Platform Flip',
    description: 'Buy the Getaway Platform Flip for ₹2,997 instead of ₹4,995.\nSave 40% on your purchase.\nGet an extra 5% OFF on prepaid payments.\nComfortable platform flip for daily wear.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-11',
    badge: 'SAVE 40%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'WOMEN FOOTWEAR',
    title: "Save 40% on Women's Getaway Chunky Glitter Platform Flip",
    description: "Get the Women's Getaway Chunky Glitter Platform Flip for ₹3,597.\nSave 40% from the original price of ₹5,995.\nSkip cash on delivery and grab 5% extra savings at checkout.\nTrendy design with all-day comfort.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-12',
    badge: 'SAVE 40%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'JIBBITZ CHARMS',
    title: 'Save 40% on Number 8 Jibbitz',
    description: 'Buy the Number 8 Jibbitz for ₹239 instead of ₹399.\nSave 40% instantly.\nEasy way to personalize your Crocs.\nLimited-time accessory offer.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-13',
    badge: 'SAVE 30%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D9488]',
    color: '#0D9488',
    type: 'JIBBITZ CHARMS',
    title: 'Save 30% on Doraemon 3-Jibbitz™',
    description: 'Get the Doraemon 3-Jibbitz™ for ₹279 instead of ₹399.\nEnjoy 30% OFF on this collectible accessory.\nClips onto your Crocs in seconds, no tools needed.\nGreat for Doraemon fans.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-14',
    badge: 'SAVE 30%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D9488]',
    color: '#0D9488',
    type: 'CLASSIC CLOGS',
    title: 'Save 30% on Classic Camouflage Clog',
    description: 'Buy the Classic Camouflage Clog for ₹3,497 instead of ₹4,995.\nSave 30% instantly.\nLightweight and comfortable design.\nPerfect for everyday casual wear.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-15',
    badge: 'SAVE 30%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D9488]',
    color: '#0D9488',
    type: 'CLASSIC CLOGS',
    title: 'Save 30% on InMotion Clog',
    description: 'Get the InMotion Clog for ₹5,247 instead of ₹7,495.\nEnjoy 30% OFF on your purchase.\nBuilt for long-lasting comfort.\nSuitable for everyday use.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-16',
    badge: 'SAVE 30%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D9488]',
    color: '#0D9488',
    type: 'ECHO CLOG',
    title: 'Save 30% on Echo Gum RO Clog',
    description: 'Buy the Echo Gum RO Clog for ₹5,597 instead of ₹7,995.\nSave 30% instantly.\nExtra 5% OFF on prepaid orders.\nModern design with premium comfort.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-17',
    badge: 'SAVE 30%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D9488]',
    color: '#0D9488',
    type: 'WOMEN FOOTWEAR',
    title: "Save 30% on Women's Brooklyn Flip",
    description: "Get the Women's Brooklyn Flip for ₹3,847 instead of ₹5,495.\nEnjoy 30% OFF instantly.\nExtra 5% OFF on prepaid payments.\nLightweight and stylish for everyday wear.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-18',
    badge: 'SAVE 30%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D9488]',
    color: '#0D9488',
    type: 'FLIP-FLOPS',
    title: 'Save 30% on Miami Flip',
    description: 'Buy the Miami Flip for ₹2,447 instead of ₹3,495.\nSave 30% on your order.\nPay upfront online and get 5% knocked off your bill.\nComfortable flip-flops for daily wear.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-19',
    badge: 'SAVE 30%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#0D9488]',
    color: '#0D9488',
    type: 'WOMEN FOOTWEAR',
    title: "Save 30% on Women's Miami Thong Flip",
    description: "Get the Women's Miami Thong Flip for ₹2,797 instead of ₹3,995.\nEnjoy 30% OFF instantly.\nExtra 5% OFF on prepaid orders.\nStylish and lightweight footwear.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-20',
    badge: 'SAVE 20%',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#00A19A]',
    color: '#00A19A',
    type: 'ECHO CLOG',
    title: 'Save 20% on Echo Wave Clog',
    description: 'Buy the Echo Wave Clog for ₹6,396 instead of ₹7,995.\nSave 20% on your purchase.\nExtra 5% OFF available on prepaid orders.\nPremium comfort with a modern design.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  },
  {
    id: 'coupon-21',
    badge: 'EXTRA 10% OFF',
    badgeType: 'PERCENT',
    badgeColor: 'bg-[#FF5722]',
    color: '#FF5722',
    type: 'PREPAID OFFER',
    title: 'Save Extra 10% on Selected Crocs Styles',
    description: "Buy selected Crocs styles like Classic Ballet and Women's Saturday Platform Sandal.\nUse code PREPAID10 to get an extra 10% OFF.\nValid on eligible prepaid orders.\nLimited-time online offer",
    code: 'PREPAID10',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Jun 2026'
  }
];
