// Coupon type
export interface Coupon {
  id: string;
  badge: string;
  badgeType: 'UP TO' | 'FLAT' | 'FREE' | 'PERCENT';
  badgeColor: string;
  color: string;
  type: string;
  title: string;
  description: string;
  code: string;
  verified: string;
  userType: string;
  validTill: string;
}

export const HANDM_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    badge: 'UP TO 75% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF2D55]',
    color: '#FF2D55',
    type: "WOMEN'S TOPS",
    title: "Women's Tops: Up to 75% Off | From ₹499",
    description: "Up to 75% off on women's tops across the latest H&M collection. Prices start from ₹499.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-2',
    badge: 'UP TO 75% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#A2845E]',
    color: '#A2845E',
    type: 'TROUSERS',
    title: 'Trousers: Up to 75% Off | From ₹299',
    description: 'Up to 75% off on H&M trousers. Prices start from ₹299 across the latest styles.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-3',
    badge: 'UP TO 70% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#000000]',
    color: '#000000',
    type: 'SITEWIDE SALE',
    title: 'Sitewide Sale: Up to 70% Off + Extra 10% Off for New Users',
    description: "Up to 70% off on the latest H&M collections across women's, men's, and kids' — plus an extra 10% off for first-time shoppers.",
    code: '',
    verified: 'Verified',
    userType: 'New & Existing Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-4',
    badge: 'UP TO 60% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#5B4FBE]',
    color: '#5B4FBE',
    type: "WOMEN'S FASHION",
    title: "Get Up to 60% Off on Women's Dresses, Tops & Ethnic Wear",
    description: "Shop the latest women's fashion collection — dresses, tops, denims & ethnic wear — at up to 60% OFF.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-5',
    badge: 'UP TO 50% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#4A3AFF]',
    color: '#0D9488',
    type: 'KIDS WEAR',
    title: 'Up to 50% Off on Kids & Baby Clothing',
    description: 'Shop playful, comfortable clothing for babies, toddlers and kids at up to 50% OFF.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-6',
    badge: 'FLAT 50% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FF9500]',
    color: '#FF9500',
    type: 'ACCESSORIES',
    title: 'Accessories: Flat 50% Off | From ₹99',
    description: 'Flat 50% off on selected H&M accessories. Prices start from ₹99.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-7',
    badge: 'FLAT 40% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FF5722]',
    color: '#FF5722',
    type: "MEN'S FASHION",
    title: "Flat 40% Off on Men's T-Shirts, Shirts & Denims",
    description: "Get a flat 40% discount across men's casual and formal wear including t-shirts, shirts, and jeans.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-8',
    badge: 'UP TO 30% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#1A1A2E]',
    color: '#1A1A2E',
    type: 'HOME & TEXTILES',
    title: 'Up to 30% Off on Home Décor & Bedding Essentials',
    description: 'Refresh your space with cushion covers, bedding sets, curtains and décor accents at up to 30% OFF.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-9',
    badge: 'FLAT 25% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#AF52DE]',
    color: '#AF52DE',
    type: 'MEMBERS EXCLUSIVE',
    title: 'Members Exclusive: Flat 25% Off on Selected Styles',
    description: 'Flat 25% off on selected H&M styles — exclusively for H&M members.',
    code: '',
    verified: 'Verified',
    userType: 'Members Only',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-10',
    badge: 'UP TO 20% OFF',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#5AC8FA]',
    color: '#5AC8FA',
    type: 'KIDS WEAR',
    title: "Baby & Kids Wear: 15% Off (All Users) | 20% Off (Plus Members)",
    description: "15% off on baby and kids' clothing for all users — Plus members get 20% off. Prices from ₹399.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-11',
    badge: 'FLAT 15% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#FF9500]',
    color: '#FF9500',
    type: "MEN'S FASHION",
    title: "Men's Fashion: Flat 15% Off | From ₹399",
    description: "Flat 15% off on a wide range of men's fashion at H&M. Prices start from ₹399.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-12',
    badge: 'FLAT 10% OFF',
    badgeType: 'FLAT',
    badgeColor: 'bg-[#007AFF]',
    color: '#007AFF',
    type: 'NEW MEMBERS',
    title: 'New H&M Members: Flat 10% Off on First Purchase (App Only)',
    description: 'Flat 10% off on your first purchase as a new H&M member — no promo code needed, discount applies automatically.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-13',
    badge: 'FROM ₹999',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#5856D6]',
    color: '#5856D6',
    type: 'INDIA STYLES',
    title: 'Hand-Picked India Styles: From ₹999',
    description: 'Distinctive H&M styles selected for the Indian market — starting from ₹999 across a range of wardrobe staples.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-14',
    badge: 'FROM ₹1,299',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#34C759]',
    color: '#34C759',
    type: "WOMEN'S JEANS",
    title: "Women's Jeans: Starting From ₹1,299",
    description: "Women's jeans at H&M starting from ₹1,299 — available in a range of fits and styles.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-15',
    badge: 'FROM ₹699',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#AF52DE]',
    color: '#AF52DE',
    type: 'LINGERIE',
    title: 'Lingerie & Underwear: Starting From ₹699',
    description: 'H&M lingerie and underwear range starting from ₹699 — bras, underwear, briefs, knickers, and shapewear.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-16',
    badge: 'FREE SHIPPING',
    badgeType: 'FREE',
    badgeColor: 'bg-[#32ADE6]',
    color: '#32ADE6',
    type: 'SHIPPING',
    title: 'Free Shipping on All Orders — No Minimum',
    description: 'Free delivery on all H&M orders today — no minimum cart value, discount applied automatically at checkout.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-17',
    badge: 'FROM ₹799',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FFCC00]',
    color: '#FFCC00',
    type: 'INDIA EXCLUSIVE',
    title: 'India Exclusive Collection: From ₹799',
    description: "Shop H&M's India-exclusive picks — tops, trousers, dresses, and more, starting from ₹799.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-18',
    badge: '100 BONUS PTS',
    badgeType: 'FREE',
    badgeColor: 'bg-[#FF3B30]',
    color: '#FF3B30',
    type: 'MEMBERSHIP',
    title: 'Join H&M Membership: 100 Bonus Points + Free Delivery',
    description: 'Become a free H&M member and get 100 welcome bonus points, free standard delivery on orders above ₹1,999, and access to member-only perks.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-19',
    badge: 'FROM ₹399',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#34C759]',
    color: '#34C759',
    type: 'TOP SELLERS',
    title: "H&M Top Sellers: From ₹399 — Men, Women & Kids",
    description: "H&M's best-selling styles for men, women, and kids starting from ₹399.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-20',
    badge: 'UNDER ₹599',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#007AFF]',
    color: '#007AFF',
    type: 'TRENDY LOOKS',
    title: 'Trendy Looks Under ₹599 | From ₹199',
    description: 'Latest H&M styles under ₹599 — prices starting from ₹199.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-21',
    badge: 'EXCLUSIVE DEALS',
    badgeType: 'FREE',
    badgeColor: 'bg-[#5856D6]',
    color: '#5856D6',
    type: 'SIGN UP',
    title: 'Sign Up & Get Exclusive New Member Discounts',
    description: 'Sign up for H&M and get exclusive deals on jeans, dresses, jackets, shoes, tops, hoodies, and more.',
    code: '',
    verified: 'Verified',
    userType: 'New Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-22',
    badge: 'FROM ₹399',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF2D55]',
    color: '#FF2D55',
    type: "MEN'S GRAPHIC TEES",
    title: "Men's Graphic & Printed T-Shirts: From ₹399",
    description: "Men's graphic tees and printed t-shirts at H&M starting from ₹399 — band tees, monochrome prints, pop culture designs, and more.",
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-23',
    badge: 'FROM ₹799',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#FF9500]',
    color: '#FF9500',
    type: 'SWEATSHIRTS & HOODIES',
    title: 'Sweatshirts & Hoodies: From ₹799',
    description: 'H&M sweatshirts and hoodies starting from ₹799 — no promo code needed.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-24',
    badge: 'FROM ₹1,499',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#AF52DE]',
    color: '#AF52DE',
    type: 'JACKETS & COATS',
    title: 'Jackets & Coats: From ₹1,499',
    description: 'H&M jackets and coats starting from ₹1,499 — faux fur, shearling, metallic shackets, oversized jackets, and calf-length coats across all sizes.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-25',
    badge: 'FROM ₹1,499',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#32ADE6]',
    color: '#32ADE6',
    type: 'DENIM COLLECTION',
    title: 'Denim Collection: From ₹1,499',
    description: 'H&M jeans starting from ₹1,499 in cotton and denim across multiple fits.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  },
  {
    id: 'coupon-26',
    badge: 'FROM ₹149',
    badgeType: 'UP TO',
    badgeColor: 'bg-[#34C759]',
    color: '#34C759',
    type: 'NEWBORN ESSENTIALS',
    title: 'Newborn Essentials: From ₹149',
    description: 'H&M newborn clothing for boys and girls aged 0–9 months, starting from ₹149 — soft, practical, and designed for everyday comfort.',
    code: '',
    verified: 'Verified',
    userType: 'All Users',
    validTill: '30 Sep 2026'
  }
];
